// DO NOT MODIFY: This file is generated by tools/generate.js. Any changes will be overwritten during the next build.

package client

import (
	"fmt"
	"reflect"

	"github.com/google/jsonapi"
	rootlygo_ "github.com/rootlyhq/rootly-go"
	rootlygo "github.com/rootlyhq/terraform-provider-rootly/v5/schema"
)

type Catalog struct {
	ID          string `jsonapi:"primary,catalogs"`
	Name        string `jsonapi:"attr,name,omitempty"`
	Description string `jsonapi:"attr,description,omitempty"`
	Icon        string `jsonapi:"attr,icon,omitempty"`
	Position    int    `jsonapi:"attr,position,omitempty"`
}

func (c *Client) ListCatalogs(params *rootlygo.ListCatalogsParams) ([]interface{}, error) {
	req, err := rootlygo.NewListCatalogsRequest(c.Rootly.Server, params)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}

	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request: %w", err)
	}

	catalogs, err := jsonapi.UnmarshalManyPayload(resp.Body, reflect.TypeOf(new(Catalog)))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling: %w", err)
	}

	return catalogs, nil
}

func (c *Client) CreateCatalog(d *Catalog) (*Catalog, error) {
	buffer, err := MarshalData(d)
	if err != nil {
		return nil, fmt.Errorf("Error marshaling catalog: %w", err)
	}

	req, err := rootlygo.NewCreateCatalogRequestWithBody(c.Rootly.Server, c.ContentType, buffer)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}
	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to perform request to create catalog: %s", err)
	}

	data, err := UnmarshalData(resp.Body, new(Catalog))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling catalog: %w", err)
	}

	return data.(*Catalog), nil
}

func (c *Client) GetCatalog(id rootlygo_.ID) (*Catalog, error) {
	req, err := rootlygo.NewGetCatalogRequest(c.Rootly.Server, id.String())
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}

	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request to get catalog: %w", err)
	}

	data, err := UnmarshalData(resp.Body, new(Catalog))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling catalog: %w", err)
	}

	return data.(*Catalog), nil
}

func (c *Client) UpdateCatalog(id rootlygo_.ID, catalog *Catalog) (*Catalog, error) {
	buffer, err := MarshalData(catalog)
	if err != nil {
		return nil, fmt.Errorf("Error marshaling catalog: %w", err)
	}

	req, err := rootlygo.NewUpdateCatalogRequestWithBody(c.Rootly.Server, id.String(), c.ContentType, buffer)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}
	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request to update catalog: %w", err)
	}

	data, err := UnmarshalData(resp.Body, new(Catalog))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling catalog: %w", err)
	}

	return data.(*Catalog), nil
}

func (c *Client) DeleteCatalog(id rootlygo_.ID) error {
	req, err := rootlygo.NewDeleteCatalogRequest(c.Rootly.Server, id.String())
	if err != nil {
		return fmt.Errorf("Error building request: %w", err)
	}

	_, err = c.Do(req)
	if err != nil {
		return fmt.Errorf("Failed to make request to delete catalog: %w", err)
	}

	return nil
}
