// DO NOT MODIFY: This file is generated by tools/generate.js. Any changes will be overwritten during the next build.

package client

import (
	"fmt"
	"net/http"
	"net/url"
	"reflect"

	"github.com/google/jsonapi"
	rootlygo "github.com/rootlyhq/terraform-provider-rootly/v5/schema"
)

type EdgeConnectorAction struct {
	ID              string                 `jsonapi:"primary,edge_connector-actions"`
	EdgeConnectorId string                 // used for URL building only, not serialized
	Name            string                 `jsonapi:"attr,name,omitempty"`
	Slug            string                 `jsonapi:"attr,slug,omitempty"`
	ActionType      string                 `jsonapi:"attr,action_type,omitempty"`
	Icon            string                 `jsonapi:"attr,icon,omitempty"`
	Description     string                 `jsonapi:"attr,description,omitempty"`
	Timeout         int                    `jsonapi:"attr,timeout,omitempty"`
	Metadata        map[string]interface{} `jsonapi:"attr,metadata,omitempty"`   // write: contains parameters
	Parameters      []interface{}          `jsonapi:"attr,parameters,omitempty"` // read: returned directly by API
	LastExecutedAt  string                 `jsonapi:"attr,last_executed_at,omitempty"`
	CreatedAt       string                 `jsonapi:"attr,created_at,omitempty"`
	UpdatedAt       string                 `jsonapi:"attr,updated_at,omitempty"`
}

func (c *Client) ListEdgeConnectorActions(edgeConnectorId string) ([]interface{}, error) {
	req, err := rootlygo.NewListEdgeConnectorActionsRequest(c.Rootly.Server, edgeConnectorId)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}

	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request: %w", err)
	}

	edge_connector_actions, err := jsonapi.UnmarshalManyPayload(resp.Body, reflect.TypeOf(new(EdgeConnectorAction)))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling: %w", err)
	}

	return edge_connector_actions, nil
}

func (c *Client) CreateEdgeConnectorAction(d *EdgeConnectorAction) (*EdgeConnectorAction, error) {
	buffer, err := MarshalData(d)
	if err != nil {
		return nil, fmt.Errorf("Error marshaling edge_connector_action: %w", err)
	}

	req, err := rootlygo.NewCreateEdgeConnectorActionRequestWithBody(c.Rootly.Server, d.EdgeConnectorId, c.ContentType, buffer)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}
	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to perform request to create edge_connector_action: %s", err)
	}

	data, err := UnmarshalData(resp.Body, new(EdgeConnectorAction))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling edge_connector_action: %w", err)
	}

	return data.(*EdgeConnectorAction), nil
}

func (c *Client) GetEdgeConnectorAction(edgeConnectorId string, id string) (*EdgeConnectorAction, error) {
	baseURL, err := url.Parse(c.Rootly.Server)
	if err != nil {
		return nil, fmt.Errorf("Error parsing server URL: %w", err)
	}

	fullURL, err := url.JoinPath(baseURL.String(), fmt.Sprintf("v1/edge_connectors/%s/actions/%s", edgeConnectorId, id))
	if err != nil {
		return nil, fmt.Errorf("Error joining URL path: %w", err)
	}

	req, err := http.NewRequest("GET", fullURL, nil)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}

	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request to get edge_connector_action: %w", err)
	}

	data, err := UnmarshalData(resp.Body, new(EdgeConnectorAction))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling edge_connector_action: %w", err)
	}

	return data.(*EdgeConnectorAction), nil
}

func (c *Client) UpdateEdgeConnectorAction(id string, edge_connector_action *EdgeConnectorAction) (*EdgeConnectorAction, error) {
	buffer, err := MarshalData(edge_connector_action)
	if err != nil {
		return nil, fmt.Errorf("Error marshaling edge_connector_action: %w", err)
	}

	baseURL, err := url.Parse(c.Rootly.Server)
	if err != nil {
		return nil, fmt.Errorf("Error parsing server URL: %w", err)
	}

	fullURL, err := url.JoinPath(baseURL.String(), fmt.Sprintf("v1/edge_connectors/%s/actions/%s", edge_connector_action.EdgeConnectorId, id))
	if err != nil {
		return nil, fmt.Errorf("Error joining URL path: %w", err)
	}

	req, err := http.NewRequest("PATCH", fullURL, buffer)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}
	req.Header.Add("Content-Type", c.ContentType)

	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request to update edge_connector_action: %w", err)
	}

	data, err := UnmarshalData(resp.Body, new(EdgeConnectorAction))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling edge_connector_action: %w", err)
	}

	return data.(*EdgeConnectorAction), nil
}

func (c *Client) DeleteEdgeConnectorAction(edgeConnectorId string, id string) error {
	baseURL, err := url.Parse(c.Rootly.Server)
	if err != nil {
		return fmt.Errorf("Error parsing server URL: %w", err)
	}

	fullURL, err := url.JoinPath(baseURL.String(), fmt.Sprintf("v1/edge_connectors/%s/actions/%s", edgeConnectorId, id))
	if err != nil {
		return fmt.Errorf("Error joining URL path: %w", err)
	}

	req, err := http.NewRequest("DELETE", fullURL, nil)
	if err != nil {
		return fmt.Errorf("Error building request: %w", err)
	}

	_, err = c.Do(req)
	if err != nil {
		return fmt.Errorf("Failed to make request to delete edge_connector_action: %w", err)
	}

	return nil
}
