// DO NOT MODIFY: This file is generated by tools/generate.js. Any changes will be overwritten during the next build.

package client

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/google/jsonapi"
)

type EdgeConnectorAction struct {
	ID   string                 `jsonapi:"primary,edge_connector_actions"`
	Data map[string]interface{} `jsonapi:"attr,data,omitempty"`
}

func (c *Client) ListEdgeConnectorActions(edgeConnectorId string) ([]interface{}, error) {
	req, err := c.Rootly.NewListEdgeConnectorActionsRequest(c.Rootly.Server, edgeConnectorId)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}

	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request: %w", err)
	}

	edge_connector_actions, err := jsonapi.UnmarshalManyPayload(resp.Body, reflect.TypeOf(new(EdgeConnectorAction)))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling: %w", err)
	}

	return edge_connector_actions, nil
}

func (c *Client) CreateEdgeConnectorAction(edgeConnectorId string, d *EdgeConnectorAction) (*EdgeConnectorAction, error) {
	buffer, err := MarshalData(d)
	if err != nil {
		return nil, fmt.Errorf("Error marshaling edge_connector_action: %w", err)
	}

	req, err := c.Rootly.NewCreateEdgeConnectorActionRequestWithBody(c.Rootly.Server, edgeConnectorId, c.ContentType, buffer)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}
	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to perform request to create edge_connector_action: %s", err)
	}

	data, err := UnmarshalData(resp.Body, new(EdgeConnectorAction))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling edge_connector_action: %w", err)
	}

	return data.(*EdgeConnectorAction), nil
}

func (c *Client) GetEdgeConnectorAction(edgeConnectorId string, actionId string) (*EdgeConnectorAction, error) {
	var idUnion struct {
		union json.RawMessage
	}
	idUnion.union, _ = json.Marshal(actionId)

	req, err := c.Rootly.NewGetEdgeConnectorActionRequest(c.Rootly.Server, edgeConnectorId, idUnion)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}

	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request to get edge_connector_action: %w", err)
	}

	data, err := UnmarshalData(resp.Body, new(EdgeConnectorAction))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling edge_connector_action: %w", err)
	}

	return data.(*EdgeConnectorAction), nil
}

func (c *Client) UpdateEdgeConnectorAction(edgeConnectorId string, actionId string, edge_connector_action *EdgeConnectorAction) (*EdgeConnectorAction, error) {
	buffer, err := MarshalData(edge_connector_action)
	if err != nil {
		return nil, fmt.Errorf("Error marshaling edge_connector_action: %w", err)
	}

	var idUnion struct {
		union json.RawMessage
	}
	idUnion.union, _ = json.Marshal(actionId)

	req, err := c.Rootly.NewUpdateEdgeConnectorActionRequestWithBody(c.Rootly.Server, edgeConnectorId, idUnion, c.ContentType, buffer)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}
	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request to update edge_connector_action: %w", err)
	}

	data, err := UnmarshalData(resp.Body, new(EdgeConnectorAction))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling edge_connector_action: %w", err)
	}

	return data.(*EdgeConnectorAction), nil
}

func (c *Client) DeleteEdgeConnectorAction(edgeConnectorId string, actionId string) error {
	var idUnion struct {
		union json.RawMessage
	}
	idUnion.union, _ = json.Marshal(actionId)

	req, err := c.Rootly.NewDeleteEdgeConnectorActionRequest(c.Rootly.Server, edgeConnectorId, idUnion)
	if err != nil {
		return fmt.Errorf("Error building request: %w", err)
	}

	_, err = c.Do(req)
	if err != nil {
		return fmt.Errorf("Failed to make request to delete edge_connector_action: %w", err)
	}

	return nil
}
