// DO NOT MODIFY: This file is generated by tools/generate.js. Any changes will be overwritten during the next build.

package client

import (
	"fmt"
	"reflect"

	"github.com/google/jsonapi"
	rootlygo "github.com/rootlyhq/terraform-provider-rootly/v2/schema"
)

type EdgeConnector struct {
	ID   string                 `jsonapi:"primary,edge_connectors"`
	Data map[string]interface{} `jsonapi:"attr,data,omitempty"`
}

func (c *Client) ListEdgeConnectors(params *rootlygo.ListEdgeConnectorsParams) ([]interface{}, error) {
	req, err := rootlygo.NewListEdgeConnectorsRequest(c.Rootly.Server, params)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}

	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request: %w", err)
	}

	edge_connectors, err := jsonapi.UnmarshalManyPayload(resp.Body, reflect.TypeOf(new(EdgeConnector)))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling: %w", err)
	}

	return edge_connectors, nil
}

func (c *Client) CreateEdgeConnector(d *EdgeConnector) (*EdgeConnector, error) {
	buffer, err := MarshalData(d)
	if err != nil {
		return nil, fmt.Errorf("Error marshaling edge_connector: %w", err)
	}

	req, err := rootlygo.NewCreateEdgeConnectorRequestWithBody(c.Rootly.Server, c.ContentType, buffer)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}
	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to perform request to create edge_connector: %s", err)
	}

	data, err := UnmarshalData(resp.Body, new(EdgeConnector))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling edge_connector: %w", err)
	}

	return data.(*EdgeConnector), nil
}

func (c *Client) GetEdgeConnector(id string) (*EdgeConnector, error) {
	req, err := rootlygo.NewGetEdgeConnectorRequest(c.Rootly.Server, id)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}

	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request to get edge_connector: %w", err)
	}

	data, err := UnmarshalData(resp.Body, new(EdgeConnector))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling edge_connector: %w", err)
	}

	return data.(*EdgeConnector), nil
}

func (c *Client) UpdateEdgeConnector(id string, edge_connector *EdgeConnector) (*EdgeConnector, error) {
	buffer, err := MarshalData(edge_connector)
	if err != nil {
		return nil, fmt.Errorf("Error marshaling edge_connector: %w", err)
	}

	req, err := rootlygo.NewUpdateEdgeConnectorRequestWithBody(c.Rootly.Server, id, c.ContentType, buffer)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}
	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request to update edge_connector: %w", err)
	}

	data, err := UnmarshalData(resp.Body, new(EdgeConnector))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling edge_connector: %w", err)
	}

	return data.(*EdgeConnector), nil
}

func (c *Client) DeleteEdgeConnector(id string) error {
	req, err := rootlygo.NewDeleteEdgeConnectorRequest(c.Rootly.Server, id)
	if err != nil {
		return fmt.Errorf("Error building request: %w", err)
	}

	_, err = c.Do(req)
	if err != nil {
		return fmt.Errorf("Failed to make request to delete edge_connector: %w", err)
	}

	return nil
}
