// DO NOT MODIFY: This file is generated by tools/generate.js. Any changes will be overwritten during the next build.

package client

import (
	"fmt"
	"reflect"

	"github.com/google/jsonapi"
	rootlygo_ "github.com/rootlyhq/rootly-go"
	rootlygo "github.com/rootlyhq/terraform-provider-rootly/v5/schema"
)

type IncidentPermissionSetResource struct {
	ID                      string `jsonapi:"primary,incident_permission_set_resources"`
	IncidentPermissionSetId string `jsonapi:"attr,incident_permission_set_id,omitempty"`
	Kind                    string `jsonapi:"attr,kind,omitempty"`
	Private                 *bool  `jsonapi:"attr,private,omitempty"`
	ResourceId              string `jsonapi:"attr,resource_id,omitempty"`
	ResourceType            string `jsonapi:"attr,resource_type,omitempty"`
}

func (c *Client) ListIncidentPermissionSetResources(id rootlygo_.ID, params *rootlygo.ListIncidentPermissionSetResourcesParams) ([]interface{}, error) {
	req, err := rootlygo.NewListIncidentPermissionSetResourcesRequest(c.Rootly.Server, id.String(), params)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}

	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request: %w", err)
	}

	incident_permission_set_resources, err := jsonapi.UnmarshalManyPayload(resp.Body, reflect.TypeOf(new(IncidentPermissionSetResource)))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling: %w", err)
	}

	return incident_permission_set_resources, nil
}

func (c *Client) CreateIncidentPermissionSetResource(d *IncidentPermissionSetResource) (*IncidentPermissionSetResource, error) {
	buffer, err := MarshalData(d)
	if err != nil {
		return nil, fmt.Errorf("Error marshaling incident_permission_set_resource: %w", err)
	}

	req, err := rootlygo.NewCreateIncidentPermissionSetResourceRequestWithBody(c.Rootly.Server, d.IncidentPermissionSetId, c.ContentType, buffer)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}
	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to perform request to create incident_permission_set_resource: %s", err)
	}

	data, err := UnmarshalData(resp.Body, new(IncidentPermissionSetResource))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling incident_permission_set_resource: %w", err)
	}

	return data.(*IncidentPermissionSetResource), nil
}

func (c *Client) GetIncidentPermissionSetResource(id rootlygo_.ID) (*IncidentPermissionSetResource, error) {
	req, err := rootlygo.NewGetIncidentPermissionSetResourceRequest(c.Rootly.Server, id.String())
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}

	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request to get incident_permission_set_resource: %w", err)
	}

	data, err := UnmarshalData(resp.Body, new(IncidentPermissionSetResource))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling incident_permission_set_resource: %w", err)
	}

	return data.(*IncidentPermissionSetResource), nil
}

func (c *Client) UpdateIncidentPermissionSetResource(id rootlygo_.ID, incident_permission_set_resource *IncidentPermissionSetResource) (*IncidentPermissionSetResource, error) {
	buffer, err := MarshalData(incident_permission_set_resource)
	if err != nil {
		return nil, fmt.Errorf("Error marshaling incident_permission_set_resource: %w", err)
	}

	req, err := rootlygo.NewUpdateIncidentPermissionSetResourceRequestWithBody(c.Rootly.Server, id.String(), c.ContentType, buffer)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}
	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request to update incident_permission_set_resource: %w", err)
	}

	data, err := UnmarshalData(resp.Body, new(IncidentPermissionSetResource))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling incident_permission_set_resource: %w", err)
	}

	return data.(*IncidentPermissionSetResource), nil
}

func (c *Client) DeleteIncidentPermissionSetResource(id rootlygo_.ID) error {
	req, err := rootlygo.NewDeleteIncidentPermissionSetResourceRequest(c.Rootly.Server, id.String())
	if err != nil {
		return fmt.Errorf("Error building request: %w", err)
	}

	_, err = c.Do(req)
	if err != nil {
		return fmt.Errorf("Failed to make request to delete incident_permission_set_resource: %w", err)
	}

	return nil
}
