// DO NOT MODIFY: This file is generated by tools/generate.js. Any changes will be overwritten during the next build.

package client

import (
	"fmt"
	"reflect"

	"github.com/google/jsonapi"
	rootlygo "github.com/rootlyhq/terraform-provider-rootly/v5/schema"
)

type StatusPageAnnouncement struct {
	ID                string `jsonapi:"primary,status_page_announcements"`
	StatusPageId      string `jsonapi:"attr,status_page_id,omitempty"`
	Title             string `jsonapi:"attr,title,omitempty"`
	Body              string `jsonapi:"attr,body,omitempty"`
	UserId            int    `jsonapi:"attr,user_id,omitempty"`
	PublishedAt       string `jsonapi:"attr,published_at,omitempty"`
	NotifySubscribers *bool  `jsonapi:"attr,notify_subscribers,omitempty"`
}

func (c *Client) ListStatusPageAnnouncements(id string, params *rootlygo.ListStatusPageAnnouncementsParams) ([]interface{}, error) {
	req, err := rootlygo.NewListStatusPageAnnouncementsRequest(c.Rootly.Server, id, params)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}

	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request: %w", err)
	}

	status_page_announcements, err := jsonapi.UnmarshalManyPayload(resp.Body, reflect.TypeOf(new(StatusPageAnnouncement)))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling: %w", err)
	}

	return status_page_announcements, nil
}

func (c *Client) CreateStatusPageAnnouncement(d *StatusPageAnnouncement) (*StatusPageAnnouncement, error) {
	buffer, err := MarshalData(d)
	if err != nil {
		return nil, fmt.Errorf("Error marshaling status_page_announcement: %w", err)
	}

	req, err := rootlygo.NewCreateStatusPageAnnouncementRequestWithBody(c.Rootly.Server, d.StatusPageId, c.ContentType, buffer)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}
	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to perform request to create status_page_announcement: %s", err)
	}

	data, err := UnmarshalData(resp.Body, new(StatusPageAnnouncement))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling status_page_announcement: %w", err)
	}

	return data.(*StatusPageAnnouncement), nil
}

func (c *Client) GetStatusPageAnnouncement(id string) (*StatusPageAnnouncement, error) {
	req, err := rootlygo.NewGetStatusPageAnnouncementRequest(c.Rootly.Server, id)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}

	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request to get status_page_announcement: %w", err)
	}

	data, err := UnmarshalData(resp.Body, new(StatusPageAnnouncement))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling status_page_announcement: %w", err)
	}

	return data.(*StatusPageAnnouncement), nil
}

func (c *Client) UpdateStatusPageAnnouncement(id string, status_page_announcement *StatusPageAnnouncement) (*StatusPageAnnouncement, error) {
	buffer, err := MarshalData(status_page_announcement)
	if err != nil {
		return nil, fmt.Errorf("Error marshaling status_page_announcement: %w", err)
	}

	req, err := rootlygo.NewUpdateStatusPageAnnouncementRequestWithBody(c.Rootly.Server, id, c.ContentType, buffer)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}
	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request to update status_page_announcement: %w", err)
	}

	data, err := UnmarshalData(resp.Body, new(StatusPageAnnouncement))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling status_page_announcement: %w", err)
	}

	return data.(*StatusPageAnnouncement), nil
}

func (c *Client) DeleteStatusPageAnnouncement(id string) error {
	req, err := rootlygo.NewDeleteStatusPageAnnouncementRequest(c.Rootly.Server, id)
	if err != nil {
		return fmt.Errorf("Error building request: %w", err)
	}

	resp, err := c.Do(req)
	if err != nil {
		return fmt.Errorf("Failed to make request to delete status_page_announcement: %w", err)
	}
	resp.Body.Close()

	return nil
}
