// DO NOT MODIFY: This file is generated by tools/generate.js. Any changes will be overwritten during the next build.

package client

import (
	"fmt"
	"reflect"

	"github.com/google/jsonapi"
	rootlygo "github.com/rootlyhq/terraform-provider-rootly/v5/schema"
)

type StatusPageComponentGroup struct {
	ID                 string `jsonapi:"primary,status_page_component_groups"`
	StatusPageId       string `jsonapi:"attr,status_page_id,omitempty"`
	Name               string `jsonapi:"attr,name,omitempty"`
	Description        string `jsonapi:"attr,description,omitempty"`
	Position           int    `jsonapi:"attr,position,omitempty"`
	CollapsedByDefault *bool  `jsonapi:"attr,collapsed_by_default,omitempty"`
}

func (c *Client) ListStatusPageComponentGroups(id string, params *rootlygo.ListStatusPageComponentGroupsParams) ([]interface{}, error) {
	req, err := rootlygo.NewListStatusPageComponentGroupsRequest(c.Rootly.Server, id, params)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}

	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request: %w", err)
	}

	status_page_component_groups, err := jsonapi.UnmarshalManyPayload(resp.Body, reflect.TypeOf(new(StatusPageComponentGroup)))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling: %w", err)
	}

	return status_page_component_groups, nil
}

func (c *Client) CreateStatusPageComponentGroup(d *StatusPageComponentGroup) (*StatusPageComponentGroup, error) {
	buffer, err := MarshalData(d)
	if err != nil {
		return nil, fmt.Errorf("Error marshaling status_page_component_group: %w", err)
	}

	req, err := rootlygo.NewCreateStatusPageComponentGroupRequestWithBody(c.Rootly.Server, d.StatusPageId, c.ContentType, buffer)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}
	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to perform request to create status_page_component_group: %s", err)
	}

	data, err := UnmarshalData(resp.Body, new(StatusPageComponentGroup))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling status_page_component_group: %w", err)
	}

	return data.(*StatusPageComponentGroup), nil
}

func (c *Client) GetStatusPageComponentGroup(id string) (*StatusPageComponentGroup, error) {
	req, err := rootlygo.NewGetStatusPageComponentGroupRequest(c.Rootly.Server, id, nil)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}

	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request to get status_page_component_group: %w", err)
	}

	data, err := UnmarshalData(resp.Body, new(StatusPageComponentGroup))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling status_page_component_group: %w", err)
	}

	return data.(*StatusPageComponentGroup), nil
}

func (c *Client) UpdateStatusPageComponentGroup(id string, status_page_component_group *StatusPageComponentGroup) (*StatusPageComponentGroup, error) {
	buffer, err := MarshalData(status_page_component_group)
	if err != nil {
		return nil, fmt.Errorf("Error marshaling status_page_component_group: %w", err)
	}

	req, err := rootlygo.NewUpdateStatusPageComponentGroupRequestWithBody(c.Rootly.Server, id, c.ContentType, buffer)
	if err != nil {
		return nil, fmt.Errorf("Error building request: %w", err)
	}
	resp, err := c.Do(req)
	if err != nil {
		return nil, fmt.Errorf("Failed to make request to update status_page_component_group: %w", err)
	}

	data, err := UnmarshalData(resp.Body, new(StatusPageComponentGroup))
	resp.Body.Close()
	if err != nil {
		return nil, fmt.Errorf("Error unmarshaling status_page_component_group: %w", err)
	}

	return data.(*StatusPageComponentGroup), nil
}

func (c *Client) DeleteStatusPageComponentGroup(id string) error {
	req, err := rootlygo.NewDeleteStatusPageComponentGroupRequest(c.Rootly.Server, id)
	if err != nil {
		return fmt.Errorf("Error building request: %w", err)
	}

	_, err = c.Do(req)
	if err != nil {
		return fmt.Errorf("Failed to make request to delete status_page_component_group: %w", err)
	}

	return nil
}
