// Code generated by rootly-providerctl. DO NOT EDIT.

package workflows

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	datasourceschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

var _ datasource.DataSource = &WorkflowGroupDataSource{}

type WorkflowGroupDataSource struct{}

func NewWorkflowGroupDataSource() datasource.DataSource {
	return &WorkflowGroupDataSource{}
}

func (d *WorkflowGroupDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_workflow_group"
}

func (d *WorkflowGroupDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasourceschema.Schema{
		Attributes: map[string]datasourceschema.Attribute{
			"id": datasourceschema.StringAttribute{
				Computed: true,
			},
			"description": datasourceschema.StringAttribute{
				MarkdownDescription: "A description of the workflow group.",
				Computed:            true,
			},
			"expanded": datasourceschema.BoolAttribute{
				MarkdownDescription: "Whether the group is expanded or collapsed.",
				Optional:            true,
				Computed:            true,
			},
			"icon": datasourceschema.StringAttribute{
				MarkdownDescription: "An emoji icon displayed next to the workflow group.",
				Computed:            true,
			},
			"kind": datasourceschema.StringAttribute{
				MarkdownDescription: "The kind of the workflow group",
				Optional:            true,
				Computed:            true,
			},
			"name": datasourceschema.StringAttribute{
				MarkdownDescription: "The name of the workflow group.",
				Optional:            true,
				Computed:            true,
			},
			"position": datasourceschema.Int64Attribute{
				MarkdownDescription: "The position of the workflow group",
				Optional:            true,
				Computed:            true,
			},
			"slug": datasourceschema.StringAttribute{
				MarkdownDescription: "The slug of the workflow group.",
				Optional:            true,
				Computed:            true,
			},
		},
	}
}

func (d *WorkflowGroupDataSource) Read(_ context.Context, _ datasource.ReadRequest, _ *datasource.ReadResponse) {
}
