// DO NOT MODIFY: This file is generated by internal/providergen/index.ts. Any changes will be overwritten during the next build.
package apiclient

type AlertRouteModel struct {
	Id              string                     `jsonapi:"primary,alert_routes,omitempty"`
	Name            string                     `jsonapi:"attribute" json:"name,omitempty"`
	Enabled         bool                       `jsonapi:"attribute" json:"enabled,omitempty"`
	AlertsSourceIds []string                   `jsonapi:"attribute" json:"alerts_source_ids,omitempty"`
	OwningTeamIds   []string                   `jsonapi:"attribute" json:"owning_team_ids,omitempty"`
	Rules           []AlertRouteModelRulesItem `jsonapi:"attribute" json:"rules,omitempty"`
}

type AlertRouteModelRulesItem struct {
	Name            string                                        `jsonapi:"attribute" json:"name,omitempty"`
	Position        int64                                         `jsonapi:"attribute" json:"position,omitempty"`
	FallbackRule    bool                                          `jsonapi:"attribute" json:"fallback_rule,omitempty"`
	Destinations    []AlertRouteModelRulesItemDestinationsItem    `jsonapi:"attribute" json:"destinations,omitempty"`
	ConditionGroups []AlertRouteModelRulesItemConditionGroupsItem `jsonapi:"attribute" json:"condition_groups,omitempty"`
}

type AlertRouteModelRulesItemDestinationsItem struct {
	TargetType string `jsonapi:"attribute" json:"target_type,omitempty"`
	TargetId   string `jsonapi:"attribute" json:"target_id,omitempty"`
}

type AlertRouteModelRulesItemConditionGroupsItem struct {
	Position   int64                                                       `jsonapi:"attribute" json:"position,omitempty"`
	Conditions []AlertRouteModelRulesItemConditionGroupsItemConditionsItem `jsonapi:"attribute" json:"conditions,omitempty"`
}

type AlertRouteModelRulesItemConditionGroupsItemConditionsItem struct {
	PropertyFieldConditionType string   `jsonapi:"attribute" json:"property_field_condition_type,omitempty"`
	PropertyFieldName          string   `jsonapi:"attribute" json:"property_field_name,omitempty"`
	PropertyFieldType          string   `jsonapi:"attribute" json:"property_field_type,omitempty"`
	PropertyFieldValue         string   `jsonapi:"attribute" json:"property_field_value,omitempty"`
	PropertyFieldValues        []string `jsonapi:"attribute" json:"property_field_values,omitempty"`
	AlertUrgencyIds            []string `jsonapi:"attribute" json:"alert_urgency_ids,omitempty"`
	ConditionableType          string   `jsonapi:"attribute" json:"conditionable_type,omitempty"`
	ConditionableId            string   `jsonapi:"attribute" json:"conditionable_id,omitempty"`
}
