// Code generated by rootly-providerctl. DO NOT EDIT.

package core

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	datasourceschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

var _ datasource.DataSource = &CustomFormDataSource{}

type CustomFormDataSource struct{}

func NewCustomFormDataSource() datasource.DataSource {
	return &CustomFormDataSource{}
}

func (d *CustomFormDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_custom_form"
}

func (d *CustomFormDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasourceschema.Schema{
		Attributes: map[string]datasourceschema.Attribute{
			"id": datasourceschema.StringAttribute{
				Computed: true,
			},
			"command": datasourceschema.StringAttribute{
				MarkdownDescription: "The Slack command used to trigger this form.",
				Optional:            true,
				Computed:            true,
			},
			"description": datasourceschema.StringAttribute{
				Computed: true,
			},
			"enabled": datasourceschema.BoolAttribute{
				Computed: true,
			},
			"name": datasourceschema.StringAttribute{
				MarkdownDescription: "The name of the custom form.",
				Optional:            true,
				Computed:            true,
			},
			"slug": datasourceschema.StringAttribute{
				MarkdownDescription: "The custom form slug. Add this to form_field.shown or form_field.required to associate form fields with custom forms.",
				Optional:            true,
				Computed:            true,
			},
		},
	}
}

func (d *CustomFormDataSource) Read(_ context.Context, _ datasource.ReadRequest, _ *datasource.ReadResponse) {
}
