// Code generated by rootly-providerctl. DO NOT EDIT.

package core

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	resourceschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &DashboardPanelResource{}

type DashboardPanelResource struct{}

func NewDashboardPanelResource() resource.Resource {
	return &DashboardPanelResource{}
}

func (r *DashboardPanelResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dashboard_panel"
}

func (r *DashboardPanelResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = resourceschema.Schema{
		Attributes: map[string]resourceschema.Attribute{
			"id": resourceschema.StringAttribute{
				Computed: true,
			},
			"dashboard_id": resourceschema.StringAttribute{
				MarkdownDescription: "The panel dashboard",
				Optional:            true,
			},
			"name": resourceschema.StringAttribute{
				MarkdownDescription: "The name of the dashboard_panel",
				Optional:            true,
			},
			"params": resourceschema.SingleNestedAttribute{
				Attributes: map[string]resourceschema.Attribute{
					"datalabels": resourceschema.SingleNestedAttribute{
						Attributes: map[string]resourceschema.Attribute{
							"enabled": resourceschema.BoolAttribute{
								Optional: true,
							},
						},
						Optional: true,
					},
					"datasets": resourceschema.ListNestedAttribute{
						NestedObject: resourceschema.NestedAttributeObject{
							Attributes: map[string]resourceschema.Attribute{
								"aggregate": resourceschema.SingleNestedAttribute{
									Attributes: map[string]resourceschema.Attribute{
										"cumulative": resourceschema.BoolAttribute{
											Optional: true,
										},
										"key": resourceschema.StringAttribute{
											Optional: true,
										},
										"operation": resourceschema.StringAttribute{
											Optional: true,
										},
									},
									Optional: true,
								},
								"collection": resourceschema.StringAttribute{
									Optional: true,
								},
								"filter": resourceschema.ListNestedAttribute{
									NestedObject: resourceschema.NestedAttributeObject{
										Attributes: map[string]resourceschema.Attribute{
											"operation": resourceschema.StringAttribute{
												Optional: true,
											},
											"rules": resourceschema.ListNestedAttribute{
												NestedObject: resourceschema.NestedAttributeObject{
													Attributes: map[string]resourceschema.Attribute{
														"condition": resourceschema.StringAttribute{
															Optional: true,
														},
														"key": resourceschema.StringAttribute{
															Optional: true,
														},
														"operation": resourceschema.StringAttribute{
															Optional: true,
														},
														"value": resourceschema.StringAttribute{
															Optional: true,
														},
													},
												},
												Optional: true,
											},
										},
									},
									Optional: true,
								},
								"name": resourceschema.StringAttribute{
									Optional: true,
								},
							},
						},
						Optional: true,
					},
					"description": resourceschema.StringAttribute{
						Optional: true,
					},
					"display": resourceschema.StringAttribute{
						Optional: true,
					},
					"legend": resourceschema.SingleNestedAttribute{
						Attributes: map[string]resourceschema.Attribute{
							"groups": resourceschema.StringAttribute{
								Optional: true,
							},
						},
						Optional: true,
					},
					"table_fields": resourceschema.ListAttribute{
						ElementType: types.StringType,
						Optional:    true,
					},
				},
				Required: true,
			},
			"position": resourceschema.SingleNestedAttribute{
				Attributes: map[string]resourceschema.Attribute{
					"h": resourceschema.Float64Attribute{
						Required: true,
					},
					"w": resourceschema.Float64Attribute{
						Required: true,
					},
					"x": resourceschema.Float64Attribute{
						Required: true,
					},
					"y": resourceschema.Float64Attribute{
						Required: true,
					},
				},
				Optional: true,
			},
		},
	}
}

func (r *DashboardPanelResource) Create(_ context.Context, _ resource.CreateRequest, _ *resource.CreateResponse) {
}

func (r *DashboardPanelResource) Read(_ context.Context, _ resource.ReadRequest, _ *resource.ReadResponse) {
}

func (r *DashboardPanelResource) Update(_ context.Context, _ resource.UpdateRequest, _ *resource.UpdateResponse) {
}

func (r *DashboardPanelResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}
