// Code generated by rootly-providerctl. DO NOT EDIT.

package core

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	resourceschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

var _ resource.Resource = &FormFieldOptionResource{}

type FormFieldOptionResource struct{}

func NewFormFieldOptionResource() resource.Resource {
	return &FormFieldOptionResource{}
}

func (r *FormFieldOptionResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_form_field_option"
}

func (r *FormFieldOptionResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = resourceschema.Schema{
		Attributes: map[string]resourceschema.Attribute{
			"id": resourceschema.StringAttribute{
				Computed: true,
			},
			"color": resourceschema.StringAttribute{
				MarkdownDescription: "The hex color of the form field option",
				Optional:            true,
			},
			"default": resourceschema.BoolAttribute{
				Optional: true,
			},
			"form_field_id": resourceschema.StringAttribute{
				MarkdownDescription: "The ID of the parent custom field",
				Required:            true,
			},
			"position": resourceschema.Int64Attribute{
				MarkdownDescription: "The position of the form field option",
				Optional:            true,
			},
			"value": resourceschema.StringAttribute{
				MarkdownDescription: "The value of the form field option",
				Required:            true,
			},
		},
	}
}

func (r *FormFieldOptionResource) Create(_ context.Context, _ resource.CreateRequest, _ *resource.CreateResponse) {
}

func (r *FormFieldOptionResource) Read(_ context.Context, _ resource.ReadRequest, _ *resource.ReadResponse) {
}

func (r *FormFieldOptionResource) Update(_ context.Context, _ resource.UpdateRequest, _ *resource.UpdateResponse) {
}

func (r *FormFieldOptionResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}
