// Code generated by rootly-providerctl. DO NOT EDIT.

package incidents

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	datasourceschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &IncidentTypeDataSource{}

type IncidentTypeDataSource struct{}

func NewIncidentTypeDataSource() datasource.DataSource {
	return &IncidentTypeDataSource{}
}

func (d *IncidentTypeDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_incident_type"
}

func (d *IncidentTypeDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasourceschema.Schema{
		Attributes: map[string]datasourceschema.Attribute{
			"id": datasourceschema.StringAttribute{
				Computed: true,
			},
			"color": datasourceschema.StringAttribute{
				MarkdownDescription: "The hex color of the incident type",
				Optional:            true,
				Computed:            true,
			},
			"description": datasourceschema.StringAttribute{
				MarkdownDescription: "The description of the incident type",
				Computed:            true,
			},
			"name": datasourceschema.StringAttribute{
				MarkdownDescription: "The name of the incident type",
				Optional:            true,
				Computed:            true,
			},
			"notify_emails": datasourceschema.ListAttribute{
				ElementType:         types.StringType,
				MarkdownDescription: "Emails to attach to the incident type",
				Computed:            true,
			},
			"position": datasourceschema.Int64Attribute{
				MarkdownDescription: "Position of the incident type",
				Computed:            true,
			},
			"properties": datasourceschema.ListNestedAttribute{
				NestedObject: datasourceschema.NestedAttributeObject{
					Attributes: map[string]datasourceschema.Attribute{
						"catalog_property_id": datasourceschema.StringAttribute{
							MarkdownDescription: "Catalog property ID",
							Computed:            true,
						},
						"value": datasourceschema.StringAttribute{
							MarkdownDescription: "The property value",
							Computed:            true,
						},
					},
				},
				MarkdownDescription: "Array of property values for this incident type.",
				Computed:            true,
			},
			"slack_aliases": datasourceschema.ListNestedAttribute{
				NestedObject: datasourceschema.NestedAttributeObject{
					Attributes: map[string]datasourceschema.Attribute{
						"id": datasourceschema.StringAttribute{
							MarkdownDescription: "Slack alias ID",
							Computed:            true,
						},
						"name": datasourceschema.StringAttribute{
							MarkdownDescription: "Slack alias name",
							Computed:            true,
						},
					},
				},
				MarkdownDescription: "Slack Aliases associated with this incident type",
				Computed:            true,
			},
			"slack_channels": datasourceschema.ListNestedAttribute{
				NestedObject: datasourceschema.NestedAttributeObject{
					Attributes: map[string]datasourceschema.Attribute{
						"id": datasourceschema.StringAttribute{
							MarkdownDescription: "Slack channel ID",
							Computed:            true,
						},
						"name": datasourceschema.StringAttribute{
							MarkdownDescription: "Slack channel name",
							Computed:            true,
						},
					},
				},
				MarkdownDescription: "Slack Channels associated with this incident type",
				Computed:            true,
			},
			"slug": datasourceschema.StringAttribute{
				MarkdownDescription: "The slug of the incident type",
				Optional:            true,
				Computed:            true,
			},
		},
	}
}

func (d *IncidentTypeDataSource) Read(_ context.Context, _ datasource.ReadRequest, _ *datasource.ReadResponse) {
}
