// Code generated by rootly-providerctl. DO NOT EDIT.

package incidents

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	resourceschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

var _ resource.Resource = &RetrospectiveProcessGroupResource{}

type RetrospectiveProcessGroupResource struct{}

func NewRetrospectiveProcessGroupResource() resource.Resource {
	return &RetrospectiveProcessGroupResource{}
}

func (r *RetrospectiveProcessGroupResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_retrospective_process_group"
}

func (r *RetrospectiveProcessGroupResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = resourceschema.Schema{
		Attributes: map[string]resourceschema.Attribute{
			"id": resourceschema.StringAttribute{
				Computed: true,
			},
			"position": resourceschema.Int64Attribute{
				Optional: true,
			},
			"retrospective_process_id": resourceschema.StringAttribute{
				Optional: true,
			},
			"sub_status_id": resourceschema.StringAttribute{
				Required: true,
			},
		},
	}
}

func (r *RetrospectiveProcessGroupResource) Create(_ context.Context, _ resource.CreateRequest, _ *resource.CreateResponse) {
}

func (r *RetrospectiveProcessGroupResource) Read(_ context.Context, _ resource.ReadRequest, _ *resource.ReadResponse) {
}

func (r *RetrospectiveProcessGroupResource) Update(_ context.Context, _ resource.UpdateRequest, _ *resource.UpdateResponse) {
}

func (r *RetrospectiveProcessGroupResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
}
