// Package rootly provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package rootly

// Defines values for DashboardPanelParamsDatasetsAggregateOperation.
const (
	DashboardPanelParamsDatasetsAggregateOperationAverage DashboardPanelParamsDatasetsAggregateOperation = "average"
	DashboardPanelParamsDatasetsAggregateOperationCount   DashboardPanelParamsDatasetsAggregateOperation = "count"
	DashboardPanelParamsDatasetsAggregateOperationSum     DashboardPanelParamsDatasetsAggregateOperation = "sum"
)

// Defines values for DashboardPanelParamsDatasetsCollection.
const (
	DashboardPanelParamsDatasetsCollectionIncidentActionItems DashboardPanelParamsDatasetsCollection = "incident_action_items"
	DashboardPanelParamsDatasetsCollectionIncidentPostMortems DashboardPanelParamsDatasetsCollection = "incident_post_mortems"
	DashboardPanelParamsDatasetsCollectionIncidents           DashboardPanelParamsDatasetsCollection = "incidents"
)

// Defines values for DashboardPanelParamsDatasetsFilterOperation.
const (
	DashboardPanelParamsDatasetsFilterOperationAnd DashboardPanelParamsDatasetsFilterOperation = "and"
	DashboardPanelParamsDatasetsFilterOperationOr  DashboardPanelParamsDatasetsFilterOperation = "or"
)

// Defines values for DashboardPanelParamsDatasetsFilterRulesCondition.
const (
	DashboardPanelParamsDatasetsFilterRulesCondition            string = "!="
	DashboardPanelParamsDatasetsFilterRulesConditionContains    string = "contains"
	DashboardPanelParamsDatasetsFilterRulesConditionEqual       string = "="
	DashboardPanelParamsDatasetsFilterRulesConditionExists      string = "exists"
	DashboardPanelParamsDatasetsFilterRulesConditionN1          string = ">="
	DashboardPanelParamsDatasetsFilterRulesConditionN2          string = "<="
	DashboardPanelParamsDatasetsFilterRulesConditionNotContains string = "not_contains"
	DashboardPanelParamsDatasetsFilterRulesConditionNotExists   string = "not_exists"
)

// Defines values for DashboardPanelParamsDatasetsFilterRulesOperation.
const (
	DashboardPanelParamsDatasetsFilterRulesOperationAnd DashboardPanelParamsDatasetsFilterRulesOperation = "and"
	DashboardPanelParamsDatasetsFilterRulesOperationOr  DashboardPanelParamsDatasetsFilterRulesOperation = "or"
)

// Defines values for DashboardPanelParamsDisplay.
const (
	DashboardPanelParamsDisplayAggregateValue     DashboardPanelParamsDisplay = "aggregate_value"
	DashboardPanelParamsDisplayColumnChart        DashboardPanelParamsDisplay = "column_chart"
	DashboardPanelParamsDisplayLineChart          DashboardPanelParamsDisplay = "line_chart"
	DashboardPanelParamsDisplayLineSteppedChart   DashboardPanelParamsDisplay = "line_stepped_chart"
	DashboardPanelParamsDisplayPieChart           DashboardPanelParamsDisplay = "pie_chart"
	DashboardPanelParamsDisplayStackedColumnChart DashboardPanelParamsDisplay = "stacked_column_chart"
	DashboardPanelParamsDisplayTable              DashboardPanelParamsDisplay = "table"
)

// Defines values for DashboardPanelListDataAttributesParamsDatasetsAggregateOperation.
const (
	DashboardPanelListDataAttributesParamsDatasetsAggregateOperationAverage DashboardPanelListDataAttributesParamsDatasetsAggregateOperation = "average"
	DashboardPanelListDataAttributesParamsDatasetsAggregateOperationCount   DashboardPanelListDataAttributesParamsDatasetsAggregateOperation = "count"
	DashboardPanelListDataAttributesParamsDatasetsAggregateOperationSum     DashboardPanelListDataAttributesParamsDatasetsAggregateOperation = "sum"
)

// Defines values for DashboardPanelListDataAttributesParamsDatasetsCollection.
const (
	DashboardPanelListDataAttributesParamsDatasetsCollectionIncidentActionItems DashboardPanelListDataAttributesParamsDatasetsCollection = "incident_action_items"
	DashboardPanelListDataAttributesParamsDatasetsCollectionIncidentPostMortems DashboardPanelListDataAttributesParamsDatasetsCollection = "incident_post_mortems"
	DashboardPanelListDataAttributesParamsDatasetsCollectionIncidents           DashboardPanelListDataAttributesParamsDatasetsCollection = "incidents"
)

// Defines values for DashboardPanelListDataAttributesParamsDatasetsFilterOperation.
const (
	DashboardPanelListDataAttributesParamsDatasetsFilterOperationAnd DashboardPanelListDataAttributesParamsDatasetsFilterOperation = "and"
	DashboardPanelListDataAttributesParamsDatasetsFilterOperationOr  DashboardPanelListDataAttributesParamsDatasetsFilterOperation = "or"
)

// Defines values for DashboardPanelListDataAttributesParamsDatasetsFilterRulesCondition.
const (
	DashboardPanelListDataAttributesParamsDatasetsFilterRulesCondition            string = "!="
	DashboardPanelListDataAttributesParamsDatasetsFilterRulesConditionContains    string = "contains"
	DashboardPanelListDataAttributesParamsDatasetsFilterRulesConditionEqual       string = "="
	DashboardPanelListDataAttributesParamsDatasetsFilterRulesConditionExists      string = "exists"
	DashboardPanelListDataAttributesParamsDatasetsFilterRulesConditionN1          string = ">="
	DashboardPanelListDataAttributesParamsDatasetsFilterRulesConditionN2          string = "<="
	DashboardPanelListDataAttributesParamsDatasetsFilterRulesConditionNotContains string = "not_contains"
	DashboardPanelListDataAttributesParamsDatasetsFilterRulesConditionNotExists   string = "not_exists"
)

// Defines values for DashboardPanelListDataAttributesParamsDatasetsFilterRulesOperation.
const (
	DashboardPanelListDataAttributesParamsDatasetsFilterRulesOperationAnd DashboardPanelListDataAttributesParamsDatasetsFilterRulesOperation = "and"
	DashboardPanelListDataAttributesParamsDatasetsFilterRulesOperationOr  DashboardPanelListDataAttributesParamsDatasetsFilterRulesOperation = "or"
)

// Defines values for DashboardPanelListDataAttributesParamsDisplay.
const (
	DashboardPanelListDataAttributesParamsDisplayAggregateValue     DashboardPanelListDataAttributesParamsDisplay = "aggregate_value"
	DashboardPanelListDataAttributesParamsDisplayColumnChart        DashboardPanelListDataAttributesParamsDisplay = "column_chart"
	DashboardPanelListDataAttributesParamsDisplayLineChart          DashboardPanelListDataAttributesParamsDisplay = "line_chart"
	DashboardPanelListDataAttributesParamsDisplayLineSteppedChart   DashboardPanelListDataAttributesParamsDisplay = "line_stepped_chart"
	DashboardPanelListDataAttributesParamsDisplayPieChart           DashboardPanelListDataAttributesParamsDisplay = "pie_chart"
	DashboardPanelListDataAttributesParamsDisplayStackedColumnChart DashboardPanelListDataAttributesParamsDisplay = "stacked_column_chart"
	DashboardPanelListDataAttributesParamsDisplayTable              DashboardPanelListDataAttributesParamsDisplay = "table"
)

// Defines values for DashboardPanelListDataType.
const (
	DashboardPanelListDataTypeDashboardPanels DashboardPanelListDataType = "dashboard_panels"
)

// Defines values for DashboardPanelResponseDataAttributesParamsDatasetsAggregateOperation.
const (
	DashboardPanelResponseDataAttributesParamsDatasetsAggregateOperationAverage DashboardPanelResponseDataAttributesParamsDatasetsAggregateOperation = "average"
	DashboardPanelResponseDataAttributesParamsDatasetsAggregateOperationCount   DashboardPanelResponseDataAttributesParamsDatasetsAggregateOperation = "count"
	DashboardPanelResponseDataAttributesParamsDatasetsAggregateOperationSum     DashboardPanelResponseDataAttributesParamsDatasetsAggregateOperation = "sum"
)

// Defines values for DashboardPanelResponseDataAttributesParamsDatasetsCollection.
const (
	DashboardPanelResponseDataAttributesParamsDatasetsCollectionIncidentActionItems DashboardPanelResponseDataAttributesParamsDatasetsCollection = "incident_action_items"
	DashboardPanelResponseDataAttributesParamsDatasetsCollectionIncidentPostMortems DashboardPanelResponseDataAttributesParamsDatasetsCollection = "incident_post_mortems"
	DashboardPanelResponseDataAttributesParamsDatasetsCollectionIncidents           DashboardPanelResponseDataAttributesParamsDatasetsCollection = "incidents"
)

// Defines values for DashboardPanelResponseDataAttributesParamsDatasetsFilterOperation.
const (
	DashboardPanelResponseDataAttributesParamsDatasetsFilterOperationAnd DashboardPanelResponseDataAttributesParamsDatasetsFilterOperation = "and"
	DashboardPanelResponseDataAttributesParamsDatasetsFilterOperationOr  DashboardPanelResponseDataAttributesParamsDatasetsFilterOperation = "or"
)

// Defines values for DashboardPanelResponseDataAttributesParamsDatasetsFilterRulesCondition.
const (
	DashboardPanelResponseDataAttributesParamsDatasetsFilterRulesCondition            string = "!="
	DashboardPanelResponseDataAttributesParamsDatasetsFilterRulesConditionContains    string = "contains"
	DashboardPanelResponseDataAttributesParamsDatasetsFilterRulesConditionEqual       string = "="
	DashboardPanelResponseDataAttributesParamsDatasetsFilterRulesConditionExists      string = "exists"
	DashboardPanelResponseDataAttributesParamsDatasetsFilterRulesConditionN1          string = ">="
	DashboardPanelResponseDataAttributesParamsDatasetsFilterRulesConditionN2          string = "<="
	DashboardPanelResponseDataAttributesParamsDatasetsFilterRulesConditionNotContains string = "not_contains"
	DashboardPanelResponseDataAttributesParamsDatasetsFilterRulesConditionNotExists   string = "not_exists"
)

// Defines values for DashboardPanelResponseDataAttributesParamsDatasetsFilterRulesOperation.
const (
	DashboardPanelResponseDataAttributesParamsDatasetsFilterRulesOperationAnd DashboardPanelResponseDataAttributesParamsDatasetsFilterRulesOperation = "and"
	DashboardPanelResponseDataAttributesParamsDatasetsFilterRulesOperationOr  DashboardPanelResponseDataAttributesParamsDatasetsFilterRulesOperation = "or"
)

// Defines values for DashboardPanelResponseDataAttributesParamsDisplay.
const (
	DashboardPanelResponseDataAttributesParamsDisplayAggregateValue     DashboardPanelResponseDataAttributesParamsDisplay = "aggregate_value"
	DashboardPanelResponseDataAttributesParamsDisplayColumnChart        DashboardPanelResponseDataAttributesParamsDisplay = "column_chart"
	DashboardPanelResponseDataAttributesParamsDisplayLineChart          DashboardPanelResponseDataAttributesParamsDisplay = "line_chart"
	DashboardPanelResponseDataAttributesParamsDisplayLineSteppedChart   DashboardPanelResponseDataAttributesParamsDisplay = "line_stepped_chart"
	DashboardPanelResponseDataAttributesParamsDisplayPieChart           DashboardPanelResponseDataAttributesParamsDisplay = "pie_chart"
	DashboardPanelResponseDataAttributesParamsDisplayStackedColumnChart DashboardPanelResponseDataAttributesParamsDisplay = "stacked_column_chart"
	DashboardPanelResponseDataAttributesParamsDisplayTable              DashboardPanelResponseDataAttributesParamsDisplay = "table"
)

// Defines values for DashboardPanelResponseDataType.
const (
	DashboardPanelResponseDataTypeDashboardPanels DashboardPanelResponseDataType = "dashboard_panels"
)

// Defines values for NewDashboardPanelDataAttributesParamsDatasetsAggregateOperation.
const (
	NewDashboardPanelDataAttributesParamsDatasetsAggregateOperationAverage NewDashboardPanelDataAttributesParamsDatasetsAggregateOperation = "average"
	NewDashboardPanelDataAttributesParamsDatasetsAggregateOperationCount   NewDashboardPanelDataAttributesParamsDatasetsAggregateOperation = "count"
	NewDashboardPanelDataAttributesParamsDatasetsAggregateOperationSum     NewDashboardPanelDataAttributesParamsDatasetsAggregateOperation = "sum"
)

// Defines values for NewDashboardPanelDataAttributesParamsDatasetsCollection.
const (
	NewDashboardPanelDataAttributesParamsDatasetsCollectionIncidentActionItems NewDashboardPanelDataAttributesParamsDatasetsCollection = "incident_action_items"
	NewDashboardPanelDataAttributesParamsDatasetsCollectionIncidentPostMortems NewDashboardPanelDataAttributesParamsDatasetsCollection = "incident_post_mortems"
	NewDashboardPanelDataAttributesParamsDatasetsCollectionIncidents           NewDashboardPanelDataAttributesParamsDatasetsCollection = "incidents"
)

// Defines values for NewDashboardPanelDataAttributesParamsDatasetsFilterOperation.
const (
	NewDashboardPanelDataAttributesParamsDatasetsFilterOperationAnd NewDashboardPanelDataAttributesParamsDatasetsFilterOperation = "and"
	NewDashboardPanelDataAttributesParamsDatasetsFilterOperationOr  NewDashboardPanelDataAttributesParamsDatasetsFilterOperation = "or"
)

// Defines values for NewDashboardPanelDataAttributesParamsDatasetsFilterRulesCondition.
const (
	NewDashboardPanelDataAttributesParamsDatasetsFilterRulesCondition            string = "!="
	NewDashboardPanelDataAttributesParamsDatasetsFilterRulesConditionContains    string = "contains"
	NewDashboardPanelDataAttributesParamsDatasetsFilterRulesConditionEqual       string = "="
	NewDashboardPanelDataAttributesParamsDatasetsFilterRulesConditionExists      string = "exists"
	NewDashboardPanelDataAttributesParamsDatasetsFilterRulesConditionN1          string = ">="
	NewDashboardPanelDataAttributesParamsDatasetsFilterRulesConditionN2          string = "<="
	NewDashboardPanelDataAttributesParamsDatasetsFilterRulesConditionNotContains string = "not_contains"
	NewDashboardPanelDataAttributesParamsDatasetsFilterRulesConditionNotExists   string = "not_exists"
)

// Defines values for NewDashboardPanelDataAttributesParamsDatasetsFilterRulesOperation.
const (
	NewDashboardPanelDataAttributesParamsDatasetsFilterRulesOperationAnd NewDashboardPanelDataAttributesParamsDatasetsFilterRulesOperation = "and"
	NewDashboardPanelDataAttributesParamsDatasetsFilterRulesOperationOr  NewDashboardPanelDataAttributesParamsDatasetsFilterRulesOperation = "or"
)

// Defines values for NewDashboardPanelDataAttributesParamsDisplay.
const (
	NewDashboardPanelDataAttributesParamsDisplayAggregateValue     NewDashboardPanelDataAttributesParamsDisplay = "aggregate_value"
	NewDashboardPanelDataAttributesParamsDisplayColumnChart        NewDashboardPanelDataAttributesParamsDisplay = "column_chart"
	NewDashboardPanelDataAttributesParamsDisplayLineChart          NewDashboardPanelDataAttributesParamsDisplay = "line_chart"
	NewDashboardPanelDataAttributesParamsDisplayLineSteppedChart   NewDashboardPanelDataAttributesParamsDisplay = "line_stepped_chart"
	NewDashboardPanelDataAttributesParamsDisplayPieChart           NewDashboardPanelDataAttributesParamsDisplay = "pie_chart"
	NewDashboardPanelDataAttributesParamsDisplayStackedColumnChart NewDashboardPanelDataAttributesParamsDisplay = "stacked_column_chart"
	NewDashboardPanelDataAttributesParamsDisplayTable              NewDashboardPanelDataAttributesParamsDisplay = "table"
)

// Defines values for NewDashboardPanelDataType.
const (
	NewDashboardPanelDataTypeDashboardPanels NewDashboardPanelDataType = "dashboard_panels"
)

// Defines values for UpdateDashboardPanelDataAttributesParamsDatasetsAggregateOperation.
const (
	Average UpdateDashboardPanelDataAttributesParamsDatasetsAggregateOperation = "average"
	Count   UpdateDashboardPanelDataAttributesParamsDatasetsAggregateOperation = "count"
	Sum     UpdateDashboardPanelDataAttributesParamsDatasetsAggregateOperation = "sum"
)

// Defines values for UpdateDashboardPanelDataAttributesParamsDatasetsFilterOperation.
const (
	UpdateDashboardPanelDataAttributesParamsDatasetsFilterOperationAnd UpdateDashboardPanelDataAttributesParamsDatasetsFilterOperation = "and"
	UpdateDashboardPanelDataAttributesParamsDatasetsFilterOperationOr  UpdateDashboardPanelDataAttributesParamsDatasetsFilterOperation = "or"
)

// Defines values for UpdateDashboardPanelDataAttributesParamsDatasetsFilterRulesOperation.
const (
	UpdateDashboardPanelDataAttributesParamsDatasetsFilterRulesOperationAnd UpdateDashboardPanelDataAttributesParamsDatasetsFilterRulesOperation = "and"
	UpdateDashboardPanelDataAttributesParamsDatasetsFilterRulesOperationOr  UpdateDashboardPanelDataAttributesParamsDatasetsFilterRulesOperation = "or"
)

// Defines values for UpdateDashboardPanelDataAttributesParamsDisplay.
const (
	AggregateValue     UpdateDashboardPanelDataAttributesParamsDisplay = "aggregate_value"
	ColumnChart        UpdateDashboardPanelDataAttributesParamsDisplay = "column_chart"
	LineChart          UpdateDashboardPanelDataAttributesParamsDisplay = "line_chart"
	LineSteppedChart   UpdateDashboardPanelDataAttributesParamsDisplay = "line_stepped_chart"
	PieChart           UpdateDashboardPanelDataAttributesParamsDisplay = "pie_chart"
	StackedColumnChart UpdateDashboardPanelDataAttributesParamsDisplay = "stacked_column_chart"
	Table              UpdateDashboardPanelDataAttributesParamsDisplay = "table"
)

// Defines values for UpdateDashboardPanelDataType.
const (
	UpdateDashboardPanelDataTypeDashboardPanels UpdateDashboardPanelDataType = "dashboard_panels"
)

// DashboardPanel defines model for dashboard_panel.
type DashboardPanel struct {
	// The panel dashboard
	DashboardId *string                   `json:"dashboard_id,omitempty"`
	Data        *[]map[string]interface{} `json:"data,omitempty"`

	// The name of the dashboard_panel
	Name   *string `json:"name"`
	Params struct {
		Datasets *[]struct {
			Aggregate *struct {
				Cumulative *bool                                           `json:"cumulative"`
				Key        *string                                         `json:"key"`
				Operation  *DashboardPanelParamsDatasetsAggregateOperation `json:"operation,omitempty"`
			} `json:"aggregate"`
			Collection *DashboardPanelParamsDatasetsCollection `json:"collection,omitempty"`
			Filter     *[]struct {
				Operation *DashboardPanelParamsDatasetsFilterOperation `json:"operation,omitempty"`
				Rules     *[]struct {
					Condition *string `json:"condition,omitempty"`
					Key       *string                                           `json:"key,omitempty"`
					Operation *DashboardPanelParamsDatasetsFilterRulesOperation `json:"operation,omitempty"`
					Value     *string                                           `json:"value,omitempty"`
				} `json:"rules,omitempty"`
			} `json:"filter,omitempty"`
			GroupBy *string `json:"group_by"`
			Name    *string `json:"name"`
		} `json:"datasets,omitempty"`
		Display *DashboardPanelParamsDisplay `json:"display,omitempty"`
	} `json:"params"`
	Position *struct {
		H float32 `json:"h"`
		W float32 `json:"w"`
		X float32 `json:"x"`
		Y float32 `json:"y"`
	} `json:"position"`
}

// DashboardPanelParamsDatasetsAggregateOperation defines model for DashboardPanel.Params.Datasets.Aggregate.Operation.
type DashboardPanelParamsDatasetsAggregateOperation string

// DashboardPanelParamsDatasetsCollection defines model for DashboardPanel.Params.Datasets.Collection.
type DashboardPanelParamsDatasetsCollection string

// DashboardPanelParamsDatasetsFilterOperation defines model for DashboardPanel.Params.Datasets.Filter.Operation.
type DashboardPanelParamsDatasetsFilterOperation string

// DashboardPanelParamsDatasetsFilterRulesOperation defines model for DashboardPanel.Params.Datasets.Filter.Rules.Operation.
type DashboardPanelParamsDatasetsFilterRulesOperation string

// DashboardPanelParamsDisplay defines model for DashboardPanel.Params.Display.
type DashboardPanelParamsDisplay string

// DashboardPanelList defines model for dashboard_panel_list.
type DashboardPanelList struct {
	Data []struct {
		Attributes struct {
			// The panel dashboard
			DashboardId *string                   `json:"dashboard_id,omitempty"`
			Data        *[]map[string]interface{} `json:"data,omitempty"`

			// The name of the dashboard_panel
			Name   *string `json:"name"`
			Params struct {
				Datasets *[]struct {
					Aggregate *struct {
						Cumulative *bool                                                             `json:"cumulative"`
						Key        *string                                                           `json:"key"`
						Operation  *DashboardPanelListDataAttributesParamsDatasetsAggregateOperation `json:"operation,omitempty"`
					} `json:"aggregate"`
					Collection *DashboardPanelListDataAttributesParamsDatasetsCollection `json:"collection,omitempty"`
					Filter     *[]struct {
						Operation *DashboardPanelListDataAttributesParamsDatasetsFilterOperation `json:"operation,omitempty"`
						Rules     *[]struct {
							Condition *string `json:"condition,omitempty"`
							Key       *string                                                             `json:"key,omitempty"`
							Operation *DashboardPanelListDataAttributesParamsDatasetsFilterRulesOperation `json:"operation,omitempty"`
							Value     *string                                                             `json:"value,omitempty"`
						} `json:"rules,omitempty"`
					} `json:"filter,omitempty"`
					GroupBy *string `json:"group_by"`
					Name    *string `json:"name"`
				} `json:"datasets,omitempty"`
				Display *DashboardPanelListDataAttributesParamsDisplay `json:"display,omitempty"`
			} `json:"params"`
			Position *struct {
				H float32 `json:"h"`
				W float32 `json:"w"`
				X float32 `json:"x"`
				Y float32 `json:"y"`
			} `json:"position"`
		} `json:"attributes"`

		// Unique ID of the dashboard_panel
		Id   string                     `json:"id"`
		Type DashboardPanelListDataType `json:"type"`
	} `json:"data"`
	Links struct {
		First string  `json:"first"`
		Last  string  `json:"last"`
		Next  *string `json:"next"`
		Prev  *string `json:"prev"`
		Self  string  `json:"self"`
	} `json:"links"`
}

// DashboardPanelListDataAttributesParamsDatasetsAggregateOperation defines model for DashboardPanelList.Data.Attributes.Params.Datasets.Aggregate.Operation.
type DashboardPanelListDataAttributesParamsDatasetsAggregateOperation string

// DashboardPanelListDataAttributesParamsDatasetsCollection defines model for DashboardPanelList.Data.Attributes.Params.Datasets.Collection.
type DashboardPanelListDataAttributesParamsDatasetsCollection string

// DashboardPanelListDataAttributesParamsDatasetsFilterOperation defines model for DashboardPanelList.Data.Attributes.Params.Datasets.Filter.Operation.
type DashboardPanelListDataAttributesParamsDatasetsFilterOperation string

// DashboardPanelListDataAttributesParamsDatasetsFilterRulesOperation defines model for DashboardPanelList.Data.Attributes.Params.Datasets.Filter.Rules.Operation.
type DashboardPanelListDataAttributesParamsDatasetsFilterRulesOperation string

// DashboardPanelListDataAttributesParamsDisplay defines model for DashboardPanelList.Data.Attributes.Params.Display.
type DashboardPanelListDataAttributesParamsDisplay string

// DashboardPanelListDataType defines model for DashboardPanelList.Data.Type.
type DashboardPanelListDataType string

// DashboardPanelResponse defines model for dashboard_panel_response.
type DashboardPanelResponse struct {
	Data struct {
		Attributes struct {
			// The panel dashboard
			DashboardId *string                   `json:"dashboard_id,omitempty"`
			Data        *[]map[string]interface{} `json:"data,omitempty"`

			// The name of the dashboard_panel
			Name   *string `json:"name"`
			Params struct {
				Datasets *[]struct {
					Aggregate *struct {
						Cumulative *bool                                                                 `json:"cumulative"`
						Key        *string                                                               `json:"key"`
						Operation  *DashboardPanelResponseDataAttributesParamsDatasetsAggregateOperation `json:"operation,omitempty"`
					} `json:"aggregate"`
					Collection *DashboardPanelResponseDataAttributesParamsDatasetsCollection `json:"collection,omitempty"`
					Filter     *[]struct {
						Operation *DashboardPanelResponseDataAttributesParamsDatasetsFilterOperation `json:"operation,omitempty"`
						Rules     *[]struct {
							Condition *string `json:"condition,omitempty"`
							Key       *string                                                                 `json:"key,omitempty"`
							Operation *string `json:"operation,omitempty"`
							Value     *string                                                                 `json:"value,omitempty"`
						} `json:"rules,omitempty"`
					} `json:"filter,omitempty"`
					GroupBy *string `json:"group_by"`
					Name    *string `json:"name"`
				} `json:"datasets,omitempty"`
				Display *DashboardPanelResponseDataAttributesParamsDisplay `json:"display,omitempty"`
			} `json:"params"`
			Position *struct {
				H float32 `json:"h"`
				W float32 `json:"w"`
				X float32 `json:"x"`
				Y float32 `json:"y"`
			} `json:"position"`
		} `json:"attributes"`

		// Unique ID of the dashboard_panel
		Id   string                         `json:"id"`
		Type DashboardPanelResponseDataType `json:"type"`
	} `json:"data"`
}

// DashboardPanelResponseDataAttributesParamsDatasetsAggregateOperation defines model for DashboardPanelResponse.Data.Attributes.Params.Datasets.Aggregate.Operation.
type DashboardPanelResponseDataAttributesParamsDatasetsAggregateOperation string

// DashboardPanelResponseDataAttributesParamsDatasetsCollection defines model for DashboardPanelResponse.Data.Attributes.Params.Datasets.Collection.
type DashboardPanelResponseDataAttributesParamsDatasetsCollection string

// DashboardPanelResponseDataAttributesParamsDatasetsFilterOperation defines model for DashboardPanelResponse.Data.Attributes.Params.Datasets.Filter.Operation.
type DashboardPanelResponseDataAttributesParamsDatasetsFilterOperation string

// DashboardPanelResponseDataAttributesParamsDatasetsFilterRulesOperation defines model for DashboardPanelResponse.Data.Attributes.Params.Datasets.Filter.Rules.Operation.
type DashboardPanelResponseDataAttributesParamsDatasetsFilterRulesOperation string

// DashboardPanelResponseDataAttributesParamsDisplay defines model for DashboardPanelResponse.Data.Attributes.Params.Display.
type DashboardPanelResponseDataAttributesParamsDisplay string

// DashboardPanelResponseDataType defines model for DashboardPanelResponse.Data.Type.
type DashboardPanelResponseDataType string

// NewDashboardPanel defines model for new_dashboard_panel.
type NewDashboardPanel struct {
	Data struct {
		Attributes struct {
			// The name of the dashboard_panel
			Name   *string `json:"name"`
			Params struct {
				Datasets *[]struct {
					Aggregate *struct {
						Cumulative *bool                                                            `json:"cumulative"`
						Key        *string                                                          `json:"key"`
						Operation  *NewDashboardPanelDataAttributesParamsDatasetsAggregateOperation `json:"operation,omitempty"`
					} `json:"aggregate"`
					Collection *NewDashboardPanelDataAttributesParamsDatasetsCollection `json:"collection,omitempty"`
					Filter     *[]struct {
						Operation *NewDashboardPanelDataAttributesParamsDatasetsFilterOperation `json:"operation,omitempty"`
						Rules     *[]struct {
							Condition *string `json:"condition,omitempty"`
							Key       *string                                                            `json:"key,omitempty"`
							Operation *string `json:"operation,omitempty"`
							Value     *string                                                            `json:"value,omitempty"`
						} `json:"rules,omitempty"`
					} `json:"filter,omitempty"`
					GroupBy *string `json:"group_by"`
					Name    *string `json:"name"`
				} `json:"datasets,omitempty"`
				Display *NewDashboardPanelDataAttributesParamsDisplay `json:"display,omitempty"`
			} `json:"params"`
			Position *struct {
				H float32 `json:"h"`
				W float32 `json:"w"`
				X float32 `json:"x"`
				Y float32 `json:"y"`
			} `json:"position"`
		} `json:"attributes"`
		Type NewDashboardPanelDataType `json:"type"`
	} `json:"data"`
}

// NewDashboardPanelDataAttributesParamsDatasetsAggregateOperation defines model for NewDashboardPanel.Data.Attributes.Params.Datasets.Aggregate.Operation.
type NewDashboardPanelDataAttributesParamsDatasetsAggregateOperation string

// NewDashboardPanelDataAttributesParamsDatasetsCollection defines model for NewDashboardPanel.Data.Attributes.Params.Datasets.Collection.
type NewDashboardPanelDataAttributesParamsDatasetsCollection string

// NewDashboardPanelDataAttributesParamsDatasetsFilterOperation defines model for NewDashboardPanel.Data.Attributes.Params.Datasets.Filter.Operation.
type NewDashboardPanelDataAttributesParamsDatasetsFilterOperation string

// NewDashboardPanelDataAttributesParamsDatasetsFilterRulesOperation defines model for NewDashboardPanel.Data.Attributes.Params.Datasets.Filter.Rules.Operation.
type NewDashboardPanelDataAttributesParamsDatasetsFilterRulesOperation string

// NewDashboardPanelDataAttributesParamsDisplay defines model for NewDashboardPanel.Data.Attributes.Params.Display.
type NewDashboardPanelDataAttributesParamsDisplay string

// NewDashboardPanelDataType defines model for NewDashboardPanel.Data.Type.
type NewDashboardPanelDataType string

// UpdateDashboardPanel defines model for update_dashboard_panel.
type UpdateDashboardPanel struct {
	Data struct {
		Attributes *struct {
			// The name of the dashboard_panel
			Name   *string `json:"name"`
			Params *struct {
				Datasets *[]struct {
					Aggregate *struct {
						Cumulative *bool                                                               `json:"cumulative"`
						Key        *string                                                             `json:"key"`
						Operation  *UpdateDashboardPanelDataAttributesParamsDatasetsAggregateOperation `json:"operation,omitempty"`
					} `json:"aggregate"`
					Collection *string `json:"collection,omitempty"`
					Filter     *[]struct {
						Operation *string `json:"operation,omitempty"`
						Rules     *[]struct {
							Condition *string `json:"condition,omitempty"`
							Key       *string                                                               `json:"key,omitempty"`
							Operation *string `json:"operation,omitempty"`
							Value     *string                                                               `json:"value,omitempty"`
						} `json:"rules,omitempty"`
					} `json:"filter,omitempty"`
					GroupBy *string `json:"group_by"`
					Name    *string `json:"name"`
				} `json:"datasets,omitempty"`
				Display *UpdateDashboardPanelDataAttributesParamsDisplay `json:"display,omitempty"`
			} `json:"params,omitempty"`
			Position *struct {
				H float32 `json:"h"`
				W float32 `json:"w"`
				X float32 `json:"x"`
				Y float32 `json:"y"`
			} `json:"position"`
		} `json:"attributes,omitempty"`
		Type *UpdateDashboardPanelDataType `json:"type,omitempty"`
	} `json:"data"`
}

// UpdateDashboardPanelDataAttributesParamsDatasetsAggregateOperation defines model for UpdateDashboardPanel.Data.Attributes.Params.Datasets.Aggregate.Operation.
type UpdateDashboardPanelDataAttributesParamsDatasetsAggregateOperation string

// UpdateDashboardPanelDataAttributesParamsDatasetsFilterOperation defines model for UpdateDashboardPanel.Data.Attributes.Params.Datasets.Filter.Operation.
type UpdateDashboardPanelDataAttributesParamsDatasetsFilterOperation string

// UpdateDashboardPanelDataAttributesParamsDatasetsFilterRulesOperation defines model for UpdateDashboardPanel.Data.Attributes.Params.Datasets.Filter.Rules.Operation.
type UpdateDashboardPanelDataAttributesParamsDatasetsFilterRulesOperation string

// UpdateDashboardPanelDataAttributesParamsDisplay defines model for UpdateDashboardPanel.Data.Attributes.Params.Display.
type UpdateDashboardPanelDataAttributesParamsDisplay string

// UpdateDashboardPanelDataType defines model for UpdateDashboardPanel.Data.Type.
type UpdateDashboardPanelDataType string
