// Code generated by rootly-providerctl. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	alerts "github.com/rootlyhq/terraform-provider-rootly/v2/internal/provider/alerts"
	core "github.com/rootlyhq/terraform-provider-rootly/v2/internal/provider/core"
	incidents "github.com/rootlyhq/terraform-provider-rootly/v2/internal/provider/incidents"
	oncall "github.com/rootlyhq/terraform-provider-rootly/v2/internal/provider/oncall"
	workflows "github.com/rootlyhq/terraform-provider-rootly/v2/internal/provider/workflows"
)

func generatedResources() []func() resource.Resource {
	resources := make([]func() resource.Resource, 0)
	resources = append(resources, alerts.GeneratedResources()...)
	resources = append(resources, core.GeneratedResources()...)
	resources = append(resources, incidents.GeneratedResources()...)
	resources = append(resources, oncall.GeneratedResources()...)
	resources = append(resources, workflows.GeneratedResources()...)
	return resources
}

func generatedDataSources() []func() datasource.DataSource {
	dataSources := make([]func() datasource.DataSource, 0)
	dataSources = append(dataSources, alerts.GeneratedDataSources()...)
	dataSources = append(dataSources, core.GeneratedDataSources()...)
	dataSources = append(dataSources, incidents.GeneratedDataSources()...)
	dataSources = append(dataSources, oncall.GeneratedDataSources()...)
	dataSources = append(dataSources, workflows.GeneratedDataSources()...)
	return dataSources
}
