// Code generated by providergen. DO NOT EDIT.
package provider

import "github.com/hashicorp/terraform-plugin-framework/resource"

var RootlyProviderGeneratedResources = []func() resource.Resource{
	NewEscalationPolicyResource,
}
