// DO NOT MODIFY: This file is generated by tools/generate.js. Any changes will be overwritten during the next build.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/rootlyhq/terraform-provider-rootly/v2/client"
	rootlygo "github.com/rootlyhq/terraform-provider-rootly/v2/schema"
)

func dataSourceFormSetCondition() *schema.Resource {
	return &schema.Resource{
		ReadContext: dataSourceFormSetConditionRead,
		Schema: map[string]*schema.Schema{
			"id": &schema.Schema{
				Type:     schema.TypeString,
				Computed: true,
			},

			"form_field_id": &schema.Schema{
				Type:     schema.TypeString,
				Computed: true,
				Optional: true,
			},
		},
	}
}

func dataSourceFormSetConditionRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*client.Client)

	params := new(rootlygo.ListFormSetConditionsParams)
	page_size := 1
	params.PageSize = &page_size

	if value, ok := d.GetOkExists("form_field_id"); ok {
		form_field_id := value.(string)
		params.FilterFormFieldId = &form_field_id
	}

	form_set_id := d.Get("form_set_id").(string)
	items, err := c.ListFormSetConditions(form_set_id, params)
	if err != nil {
		return diag.FromErr(err)
	}

	if len(items) == 0 {
		return diag.Errorf("form_set_condition not found")
	}
	item, _ := items[0].(*client.FormSetCondition)

	d.SetId(item.ID)
	d.Set("form_field_id", item.FormFieldId)
	return nil
}
