// DO NOT MODIFY: This file is generated by tools/generate.js. Any changes will be overwritten during the next build.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccDataSourceAlertField(t *testing.T) {
	resource.UnitTest(t, resource.TestCase{
		IsUnitTest: false,
		PreCheck: func() {
			testAccPreCheck(t)
		},
		ProviderFactories: providerFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceAlertField,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.rootly_alert_field.test", "name", "test-field"),
				),
			},
		},
	})
}

const testAccDataSourceAlertField = `
resource "rootly_alert_field" "test" {
	name = "test-field"
}

data "rootly_alert_field" "test" {
	name = rootly_alert_field.test.name
}
`