// DO NOT MODIFY: This file is generated by tools/generate.js. Any changes will be overwritten during the next build.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/rootlyhq/terraform-provider-rootly/v2/client"
	rootlygo "github.com/rootlyhq/terraform-provider-rootly/v2/schema"
)

func dataSourceWorkflowGroup() *schema.Resource {
	return &schema.Resource{
		ReadContext: dataSourceWorkflowGroupRead,
		Schema: map[string]*schema.Schema{
			"id": &schema.Schema{
				Type:     schema.TypeString,
				Computed: true,
			},

			"kind": &schema.Schema{
				Type:         schema.TypeString,
				Computed:     true,
				Optional:     true,
				ValidateFunc: validation.StringInSlice([]string{"simple", "incident", "post_mortem", "action_item", "pulse", "alert"}, false),
			},

			"name": &schema.Schema{
				Type:     schema.TypeString,
				Computed: true,
				Optional: true,
			},

			"slug": &schema.Schema{
				Type:     schema.TypeString,
				Computed: true,
				Optional: true,
			},

			"expanded": &schema.Schema{
				Type:     schema.TypeBool,
				Computed: true,
				Optional: true,
			},

			"position": &schema.Schema{
				Type:     schema.TypeInt,
				Computed: true,
				Optional: true,
			},
		},
	}
}

func dataSourceWorkflowGroupRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*client.Client)

	params := new(rootlygo.ListWorkflowGroupsParams)
	page_size := 1
	params.PageSize = &page_size

	if value, ok := d.GetOkExists("name"); ok {
		name := value.(string)
		params.FilterName = &name
	}

	if value, ok := d.GetOkExists("slug"); ok {
		slug := value.(string)
		params.FilterSlug = &slug
	}

	if value, ok := d.GetOkExists("kind"); ok {
		kind := value.(string)
		params.FilterKind = &kind
	}

	if value, ok := d.GetOkExists("expanded"); ok {
		expanded := value.(bool)
		params.FilterExpanded = &expanded
	}

	if value, ok := d.GetOkExists("position"); ok {
		position := value.(int)
		params.FilterPosition = &position
	}

	items, err := c.ListWorkflowGroups(params)
	if err != nil {
		return diag.FromErr(err)
	}

	if len(items) == 0 {
		return diag.Errorf("workflow_group not found")
	}
	item, _ := items[0].(*client.WorkflowGroup)

	d.SetId(item.ID)
	d.Set("name", item.Name)
	d.Set("slug", item.Slug)
	d.Set("kind", item.Kind)
	d.Set("expanded", item.Expanded)
	d.Set("position", item.Position)
	return nil
}
