// DO NOT MODIFY: This file is generated by tools/generate.js. Any changes will be overwritten during the next build.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccResourceOnCallRole(t *testing.T) {
	resource.UnitTest(t, resource.TestCase{
		PreCheck: func() {
			testAccPreCheck(t)
		},
		ProviderFactories: providerFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccResourceOnCallRoleCreate,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("rootly_on_call_role.test", "alert_sources_permissions.0", "read"),
					resource.TestCheckResourceAttr("rootly_on_call_role.test", "alert_sources_permissions.1", "create"),
					resource.TestCheckResourceAttr("rootly_on_call_role.test", "alert_sources_permissions.2", "update"),
					resource.TestCheckNoResourceAttr("rootly_on_call_role.test", "alert_sources_permissions.3"),
				),
			},
			{
				Config: testAccResourceOnCallRoleUpdate,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("rootly_on_call_role.test", "alert_sources_permissions.0", "read"),
					resource.TestCheckResourceAttr("rootly_on_call_role.test", "alert_sources_permissions.1", "create"),
					resource.TestCheckResourceAttr("rootly_on_call_role.test", "alert_sources_permissions.2", "update"),
					resource.TestCheckResourceAttr("rootly_on_call_role.test", "alert_sources_permissions.3", "delete"),
				),
			},
		},
	})
}

const testAccResourceOnCallRoleCreate = `
resource "rootly_on_call_role" "test" {
	name = "test different name"
	system_role = "custom"
	alert_sources_permissions = ["read", "create", "update"]
}
`

const testAccResourceOnCallRoleUpdate = `
resource "rootly_on_call_role" "test" {
	name = "test different name"
	system_role = "custom"
	alert_sources_permissions = ["read", "create", "update", "delete"]
}
`
