// DO NOT MODIFY: This file is generated by tools/generate.js. Any changes will be overwritten during the next build.

package provider

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/acctest"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccResourceCustomForm(t *testing.T) {
	customFormName := acctest.RandomWithPrefix("tf-custom-form")
	customFormCommand := acctest.RandomWithPrefix("tf-custom-form-command")
	resource.UnitTest(t, resource.TestCase{
		PreCheck: func() {
			testAccPreCheck(t)
		},
		ProviderFactories: providerFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccResourceCustomFormConfig(customFormName, customFormCommand),
			},
		},
	})
}

func testAccResourceCustomFormConfig(customFormName, customFormCommand string) string {
	return fmt.Sprintf(`
resource "rootly_custom_form" "test" {
	name = "%s"
	command = "%s"
}
`, customFormName, customFormCommand)
}
