package provider

// This file was auto-generated by tools/gen_tasks.js

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccResourceWorkflowTaskSendSlackMessage(t *testing.T) {
	resource.UnitTest(t, resource.TestCase{
		PreCheck: func() {
			testAccPreCheck(t)
		},
		ProviderFactories: providerFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccResourceWorkflowTaskSendSlackMessage,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("rootly_workflow_incident.test", "name", "test-workflow"),
				),
			},
		},
	})
}

const testAccResourceWorkflowTaskSendSlackMessage = `
data "rootly_severity" "sev0" {
	slug = "sev0"
}

resource "rootly_workflow_incident" "test" {
  name = "test-workflow"
	trigger_params {
		triggers = ["incident_updated"]
	}
}

resource "rootly_workflow_task_send_slack_message" "test" {
	workflow_id = rootly_workflow_incident.test.id
	task_params {
		text = data.rootly_severity.sev0.id
	}
}
`
