// DO NOT MODIFY: This file is generated by tools/generate.js. Any changes will be overwritten during the next build.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccResourceAlertRoute(t *testing.T) {
	resource.UnitTest(t, resource.TestCase{
		IsUnitTest: false,
		PreCheck: func() {
			testAccPreCheck(t)
		},
		ProviderFactories: providerFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccResourceAlertRouteCreate,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("rootly_alert_route.test", "name", "test-route"),
					resource.TestCheckResourceAttr("rootly_alert_route.test", "enabled", "true"),
				),
			},
			{
				Config: testAccResourceAlertRouteUpdate,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("rootly_alert_route.test", "name", "test-route-updated"),
					resource.TestCheckResourceAttr("rootly_alert_route.test", "enabled", "false"),
				),
			},
		},
	})
}

const testAccResourceAlertRouteCreate = `
data "rootly_alerts_source" "test" {
  source_type = "generic_webhook"
}

resource "rootly_team" "test" {
	name = "Test Team Alert Route"
}

resource "rootly_alert_route" "test" {
	name = "test-route"
	enabled = true
	alerts_source_ids = [data.rootly_alerts_source.test.id]
	owner_group_ids = [rootly_team.test.id]
}
`

const testAccResourceAlertRouteUpdate = `
data "rootly_alerts_source" "test" {
  source_type = "generic_webhook"
}

resource "rootly_team" "test" {
	name = "Test Team Alert Route"
}

resource "rootly_alert_route" "test" {
	name = "test-route-updated"
	enabled = false
	alerts_source_ids = [data.rootly_alerts_source.test.id]
	owner_group_ids = [rootly_team.test.id]
}
`