package provider

// This file was auto-generated by tools/generate-tasks.js

import (
	"fmt"
	"testing"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/acctest"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccResourceWorkflowTaskUpdateClickupTask(t *testing.T) {
	t.Parallel()
	rName := acctest.RandomWithPrefix("tf-wf-task")

	resource.UnitTest(t, resource.TestCase{
		PreCheck:          func() {
			testAccPreCheck(t)
		},
		ProviderFactories: providerFactories,
		Steps: []resource.TestStep {
			{
				Config: testAccResourceWorkflowTaskUpdateClickupTaskConfig(rName),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("rootly_workflow_incident.foo", "name", rName),
				),
			},
			{
				Config: testAccResourceWorkflowTaskUpdateClickupTaskUpdateConfig(rName),
			},
		},
	})
}

func testAccResourceWorkflowTaskUpdateClickupTaskConfig(name string) string {
	return fmt.Sprintf(`
resource "rootly_workflow_incident" "foo" {
  	name = "%s"
	trigger_params {
		triggers = ["incident_updated"]
	}
}

resource "rootly_workflow_task_update_clickup_task" "foo" {
	workflow_id = rootly_workflow_incident.foo.id
	task_params {
		task_id = "test"
	}
}
`, name)
}

func testAccResourceWorkflowTaskUpdateClickupTaskUpdateConfig(name string) string {
	return fmt.Sprintf(`
resource "rootly_workflow_incident" "foo" {
  	name = "%s"
	trigger_params {
		triggers = ["incident_updated"]
	}
}

resource "rootly_workflow_task_update_clickup_task" "foo" {
	workflow_id = rootly_workflow_incident.foo.id
	task_params {
		task_id = "test"
	}
}
`, name)
}
