// DO NOT MODIFY: This file is generated by tools/generate.js. Any changes will be overwritten during the next build.

package provider

import (
	"context"
	"errors"
	"fmt"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/rootlyhq/terraform-provider-rootly/v2/client"
	"github.com/rootlyhq/terraform-provider-rootly/v2/tools"
)

func resourceAlertRoute() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourceAlertRouteCreate,
		ReadContext:   resourceAlertRouteRead,
		UpdateContext: resourceAlertRouteUpdate,
		DeleteContext: resourceAlertRouteDelete,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
		Schema: map[string]*schema.Schema{

			"name": &schema.Schema{
				Type:        schema.TypeString,
				Computed:    false,
				Required:    true,
				Optional:    false,
				ForceNew:    false,
				Description: "The name of the alert route",
			},

			"enabled": &schema.Schema{
				Type:     schema.TypeBool,
				Default:  true,
				Optional: true,
			},

			"alerts_source_ids": &schema.Schema{
				Type: schema.TypeList,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
				DiffSuppressFunc: tools.EqualIgnoringOrder,
				Computed:         false,
				Required:         true,
				Optional:         false,
				Description:      "",
			},

			"owner_group_ids": &schema.Schema{
				Type: schema.TypeList,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
				DiffSuppressFunc: tools.EqualIgnoringOrder,
				Computed:         false,
				Required:         false,
				Optional:         true,
				Description:      "",
			},

			"alert_routing_rules_attributes": &schema.Schema{
				Type:             schema.TypeList,
				Computed:         false,
				Required:         true,
				Optional:         false,
				Description:      "",
				DiffSuppressFunc: tools.EqualIgnoringOrder,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{

						"id": &schema.Schema{
							Type:        schema.TypeString,
							Computed:    true,
							Required:    false,
							Optional:    true,
							ForceNew:    false,
							Description: "Unique ID of the alert routing rule",
						},

						"name": &schema.Schema{
							Type:        schema.TypeString,
							Computed:    true,
							Required:    false,
							Optional:    true,
							ForceNew:    false,
							Description: "The name of the alert routing rule",
						},

						"enabled": &schema.Schema{
							Type:     schema.TypeBool,
							Default:  true,
							Optional: true,
						},

						"position": &schema.Schema{
							Type:        schema.TypeInt,
							Computed:    true,
							Required:    false,
							Optional:    true,
							ForceNew:    false,
							Description: "The position of the alert routing rule for ordering evaluation",
						},

						"condition_type": &schema.Schema{
							Type:         schema.TypeString,
							Default:      "all",
							Required:     false,
							Optional:     true,
							ForceNew:     false,
							Description:  "The type of condition for the alert routing rule. Value must be one of `all`, `any`.",
							ValidateFunc: validation.StringInSlice([]string{"all", "any"}, false),
						},

						"fallback_rule": &schema.Schema{
							Type:        schema.TypeBool,
							Computed:    true,
							Required:    false,
							Optional:    true,
							Description: "Whether this is a fallback rule. Value must be one of true or false",
						},

						"alert_routing_rule_targets": &schema.Schema{
							Type:             schema.TypeList,
							Computed:         false,
							Required:         false,
							Optional:         true,
							Description:      "",
							DiffSuppressFunc: tools.EqualIgnoringOrder,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{

									"id": &schema.Schema{
										Type:        schema.TypeString,
										Computed:    true,
										Required:    false,
										Optional:    true,
										ForceNew:    false,
										Description: "Unique ID of the target",
									},

									"name": &schema.Schema{
										Type:        schema.TypeString,
										Computed:    true,
										Required:    false,
										Optional:    true,
										ForceNew:    false,
										Description: "The name of the alert routing rule target",
									},

									"target_type": &schema.Schema{
										Type:         schema.TypeString,
										Default:      "Service",
										Required:     false,
										Optional:     true,
										ForceNew:     false,
										Description:  "The type of the target. Value must be one of `Service`, `Group`, `EscalationPolicy`.",
										ValidateFunc: validation.StringInSlice([]string{"Service", "Group", "EscalationPolicy"}, false),
									},

									"target_id": &schema.Schema{
										Type:        schema.TypeString,
										Computed:    true,
										Required:    false,
										Optional:    true,
										ForceNew:    false,
										Description: "The ID of the target",
									},

									"created_at": &schema.Schema{
										Type:        schema.TypeString,
										Computed:    true,
										Required:    false,
										Optional:    true,
										ForceNew:    false,
										Description: "Date of creation",
									},

									"updated_at": &schema.Schema{
										Type:        schema.TypeString,
										Computed:    true,
										Required:    false,
										Optional:    true,
										ForceNew:    false,
										Description: "Date of last update",
									},
								},
							},
						},

						"alert_routing_rule_condition_groups": &schema.Schema{
							Type:             schema.TypeList,
							Computed:         false,
							Required:         false,
							Optional:         true,
							Description:      "",
							DiffSuppressFunc: tools.EqualIgnoringOrder,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{

									"id": &schema.Schema{
										Type:        schema.TypeString,
										Computed:    true,
										Required:    false,
										Optional:    true,
										ForceNew:    false,
										Description: "Unique ID of the condition group",
									},

									"position": &schema.Schema{
										Type:        schema.TypeInt,
										Computed:    true,
										Required:    false,
										Optional:    true,
										ForceNew:    false,
										Description: "The position of the condition group",
									},

									"alert_routing_rule_conditions": &schema.Schema{
										Type:             schema.TypeList,
										Computed:         false,
										Required:         false,
										Optional:         true,
										Description:      "",
										DiffSuppressFunc: tools.EqualIgnoringOrder,
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{

												"id": &schema.Schema{
													Type:        schema.TypeString,
													Computed:    true,
													Required:    false,
													Optional:    true,
													ForceNew:    false,
													Description: "Unique ID of the condition",
												},

												"property_class": &schema.Schema{
													Type:        schema.TypeString,
													Computed:    true,
													Required:    false,
													Optional:    true,
													ForceNew:    false,
													Description: "The class context for the property (e.g., 'Alert')",
												},

												"property_field_condition_type": &schema.Schema{
													Type:         schema.TypeString,
													Default:      "is_one_of",
													Required:     false,
													Optional:     true,
													ForceNew:     false,
													Description:  "Value must be one of `is_one_of`, `is_not_one_of`, `contains`, `does_not_contain`, `starts_with`, `ends_with`, `matches_regex`, `is_empty`.",
													ValidateFunc: validation.StringInSlice([]string{"is_one_of", "is_not_one_of", "contains", "does_not_contain", "starts_with", "ends_with", "matches_regex", "is_empty"}, false),
												},

												"property_field_name": &schema.Schema{
													Type:        schema.TypeString,
													Computed:    true,
													Required:    false,
													Optional:    true,
													ForceNew:    false,
													Description: "The name of the property field",
												},

												"property_field_type": &schema.Schema{
													Type:         schema.TypeString,
													Default:      "attribute",
													Required:     false,
													Optional:     true,
													ForceNew:     false,
													Description:  "Value must be one of `attribute`, `payload`, `alert_field`.",
													ValidateFunc: validation.StringInSlice([]string{"attribute", "payload", "alert_field"}, false),
												},

												"property_field_value": &schema.Schema{
													Type:        schema.TypeString,
													Computed:    true,
													Required:    false,
													Optional:    true,
													ForceNew:    false,
													Description: "The value of the property field",
												},

												"property_field_values": &schema.Schema{
													Type: schema.TypeList,
													Elem: &schema.Schema{
														Type: schema.TypeString,
													},
													DiffSuppressFunc: tools.EqualIgnoringOrder,
													Computed:         false,
													Required:         false,
													Optional:         true,
													Description:      "",
												},

												"alert_urgency_ids": &schema.Schema{
													Type: schema.TypeList,
													Elem: &schema.Schema{
														Type: schema.TypeString,
													},
													DiffSuppressFunc: tools.EqualIgnoringOrder,
													Computed:         false,
													Required:         false,
													Optional:         true,
													Description:      "The Alert Urgency IDs to check in the condition",
												},

												"conditionable_type": &schema.Schema{
													Type:         schema.TypeString,
													Default:      "AlertField",
													Required:     false,
													Optional:     true,
													ForceNew:     false,
													Description:  "The type of the conditionable. Value must be one of `AlertField`.",
													ValidateFunc: validation.StringInSlice([]string{"AlertField"}, false),
												},

												"conditionable_id": &schema.Schema{
													Type:        schema.TypeString,
													Computed:    true,
													Required:    false,
													Optional:    true,
													ForceNew:    false,
													Description: "The ID of the conditionable",
												},

												"created_at": &schema.Schema{
													Type:        schema.TypeString,
													Computed:    true,
													Required:    false,
													Optional:    true,
													ForceNew:    false,
													Description: "Date of creation",
												},

												"updated_at": &schema.Schema{
													Type:        schema.TypeString,
													Computed:    true,
													Required:    false,
													Optional:    true,
													ForceNew:    false,
													Description: "Date of last update",
												},
											},
										},
									},

									"created_at": &schema.Schema{
										Type:        schema.TypeString,
										Computed:    true,
										Required:    false,
										Optional:    true,
										ForceNew:    false,
										Description: "Date of creation",
									},

									"updated_at": &schema.Schema{
										Type:        schema.TypeString,
										Computed:    true,
										Required:    false,
										Optional:    true,
										ForceNew:    false,
										Description: "Date of last update",
									},
								},
							},
						},

						"created_at": &schema.Schema{
							Type:        schema.TypeString,
							Computed:    true,
							Required:    false,
							Optional:    true,
							ForceNew:    false,
							Description: "Date of creation",
						},

						"updated_at": &schema.Schema{
							Type:        schema.TypeString,
							Computed:    true,
							Required:    false,
							Optional:    true,
							ForceNew:    false,
							Description: "Date of last update",
						},
					},
				},
			},
		},
	}
}

func resourceAlertRouteCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*client.Client)

	tflog.Trace(ctx, fmt.Sprintf("Creating AlertRoute"))

	s := &client.AlertRoute{}

	if value, ok := d.GetOkExists("name"); ok {
		s.Name = value.(string)
	}
	if value, ok := d.GetOkExists("enabled"); ok {
		s.Enabled = tools.Bool(value.(bool))
	}
	if value, ok := d.GetOkExists("alerts_source_ids"); ok {
		s.AlertsSourceIds = value.([]interface{})
	}
	if value, ok := d.GetOkExists("owner_group_ids"); ok {
		s.OwnerGroupIds = value.([]interface{})
	}
	if value, ok := d.GetOkExists("alert_routing_rules_attributes"); ok {
		s.AlertRoutingRulesAttributes = value.([]interface{})
	}

	res, err := c.CreateAlertRoute(s)
	if err != nil {
		return diag.Errorf("Error creating alert_route: %s", err.Error())
	}

	d.SetId(res.ID)
	tflog.Trace(ctx, fmt.Sprintf("created a alert_route resource: %s", d.Id()))

	return resourceAlertRouteRead(ctx, d, meta)
}

func resourceAlertRouteRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*client.Client)
	tflog.Trace(ctx, fmt.Sprintf("Reading AlertRoute: %s", d.Id()))

	item, err := c.GetAlertRoute(d.Id())
	if err != nil {
		// In the case of a NotFoundError, it means the resource may have been removed upstream
		// We just remove it from the state.
		if errors.Is(err, client.NewNotFoundError("")) && !d.IsNewResource() {
			tflog.Warn(ctx, fmt.Sprintf("AlertRoute (%s) not found, removing from state", d.Id()))
			d.SetId("")
			return nil
		}

		return diag.Errorf("Error reading alert_route: %s", d.Id())
	}

	d.Set("name", item.Name)
	d.Set("enabled", item.Enabled)
	d.Set("alerts_source_ids", item.AlertsSourceIds)
	d.Set("owner_group_ids", item.OwnerGroupIds)

	if item.AlertRoutingRulesAttributes != nil {
		processed_items_alert_routing_rules_attributes := make([]map[string]interface{}, 0)

		for _, c := range item.AlertRoutingRulesAttributes {
			if rawItem, ok := c.(map[string]interface{}); ok {
				// Create a new map with only the fields defined in the schema
				processed_item_alert_routing_rules_attributes := map[string]interface{}{
					"id":                                  rawItem["id"],
					"name":                                rawItem["name"],
					"enabled":                             rawItem["enabled"],
					"position":                            rawItem["position"],
					"condition_type":                      rawItem["condition_type"],
					"fallback_rule":                       rawItem["fallback_rule"],
					"alert_routing_rule_targets":          rawItem["alert_routing_rule_targets"],
					"alert_routing_rule_condition_groups": rawItem["alert_routing_rule_condition_groups"],
					"created_at":                          rawItem["created_at"],
					"updated_at":                          rawItem["updated_at"],
				}
				processed_items_alert_routing_rules_attributes = append(processed_items_alert_routing_rules_attributes, processed_item_alert_routing_rules_attributes)
			}
		}

		d.Set("alert_routing_rules_attributes", processed_items_alert_routing_rules_attributes)
	} else {
		d.Set("alert_routing_rules_attributes", nil)
	}

	return nil
}

func resourceAlertRouteUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*client.Client)
	tflog.Trace(ctx, fmt.Sprintf("Updating AlertRoute: %s", d.Id()))

	s := &client.AlertRoute{}

	if d.HasChange("name") {
		s.Name = d.Get("name").(string)
	}
	if d.HasChange("enabled") {
		s.Enabled = tools.Bool(d.Get("enabled").(bool))
	}

	if d.HasChange("alerts_source_ids") {
		if value, ok := d.GetOk("alerts_source_ids"); value != nil && ok {
			s.AlertsSourceIds = value.([]interface{})
		} else {
			s.AlertsSourceIds = []interface{}{}
		}
	}

	if d.HasChange("owner_group_ids") {
		if value, ok := d.GetOk("owner_group_ids"); value != nil && ok {
			s.OwnerGroupIds = value.([]interface{})
		} else {
			s.OwnerGroupIds = []interface{}{}
		}
	}

	if d.HasChange("alert_routing_rules_attributes") {
		if value, ok := d.GetOk("alert_routing_rules_attributes"); value != nil && ok {
			s.AlertRoutingRulesAttributes = value.([]interface{})
		} else {
			s.AlertRoutingRulesAttributes = []interface{}{}
		}
	}

	_, err := c.UpdateAlertRoute(d.Id(), s)
	if err != nil {
		return diag.Errorf("Error updating alert_route: %s", err.Error())
	}

	return resourceAlertRouteRead(ctx, d, meta)
}

func resourceAlertRouteDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*client.Client)
	tflog.Trace(ctx, fmt.Sprintf("Deleting AlertRoute: %s", d.Id()))

	err := c.DeleteAlertRoute(d.Id())
	if err != nil {
		// In the case of a NotFoundError, it means the resource may have been removed upstream.
		// We just remove it from the state.
		if errors.Is(err, client.NewNotFoundError("")) && !d.IsNewResource() {
			tflog.Warn(ctx, fmt.Sprintf("AlertRoute (%s) not found, removing from state", d.Id()))
			d.SetId("")
			return nil
		}
		return diag.Errorf("Error deleting alert_route: %s", err.Error())
	}

	d.SetId("")

	return nil
}
