package provider

// This file was auto-generated by tools/gen_tasks.js

import (
	"testing"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccResourceWorkflowTaskAutoAssignRoleVictorOps(t *testing.T) {
	resource.UnitTest(t, resource.TestCase{
		PreCheck:          func() {
			testAccPreCheck(t)
		},
		ProviderFactories: providerFactories,
		Steps: []resource.TestStep {
			{
				Config: testAccResourceWorkflowTaskAutoAssignRoleVictorOps,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("rootly_workflow_incident.foo", "name", "test-workflow"),
				),
			},
			{
				Config: testAccResourceWorkflowTaskAutoAssignRoleVictorOpsUpdate,
			},
		},
	})
}

const testAccResourceWorkflowTaskAutoAssignRoleVictorOps = `
resource "rootly_workflow_incident" "foo" {
  	name = "test-workflow"
	trigger_params {
		triggers = ["incident_updated"]
	}
}

resource "rootly_workflow_task_auto_assign_role_victor_ops" "foo" {
	workflow_id = rootly_workflow_incident.foo.id
	task_params {
		incident_role_id = "test"
team = {
					id = "foo"
					name = "bar"
				}
	}
}
`

const testAccResourceWorkflowTaskAutoAssignRoleVictorOpsUpdate = `
resource "rootly_workflow_incident" "foo" {
  	name = "test-workflow"
	trigger_params {
		triggers = ["incident_updated"]
	}
}

resource "rootly_workflow_task_auto_assign_role_victor_ops" "foo" {
	workflow_id = rootly_workflow_incident.foo.id
	task_params {
		incident_role_id = "test"
team = {
					id = "foo"
					name = "bar"
				}
	}
}
`
