// DO NOT MODIFY: This file is generated by tools/generate.js. Any changes will be overwritten during the next build.

package provider

import (
	"context"
	"errors"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/rootlyhq/terraform-provider-rootly/v5/client"
	"github.com/rootlyhq/terraform-provider-rootly/v5/tools"
)

func resourceStatusPageComponentGroup() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourceStatusPageComponentGroupCreate,
		ReadContext:   resourceStatusPageComponentGroupRead,
		UpdateContext: resourceStatusPageComponentGroupUpdate,
		DeleteContext: resourceStatusPageComponentGroupDelete,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
		Schema: map[string]*schema.Schema{

			"status_page_id": &schema.Schema{
				Type:        schema.TypeString,
				Computed:    false,
				Required:    true,
				Optional:    false,
				Sensitive:   false,
				ForceNew:    true,
				WriteOnly:   false,
				Description: "",
			},

			"name": &schema.Schema{
				Type:        schema.TypeString,
				Computed:    false,
				Required:    true,
				Optional:    false,
				Sensitive:   false,
				ForceNew:    false,
				WriteOnly:   false,
				Description: "Name of the component group",
			},

			"description": &schema.Schema{
				Type:        schema.TypeString,
				Computed:    true,
				Required:    false,
				Optional:    true,
				Sensitive:   false,
				ForceNew:    false,
				WriteOnly:   false,
				Description: "Description of the component group",
			},

			"position": &schema.Schema{
				Type:        schema.TypeInt,
				Computed:    true,
				Required:    false,
				Optional:    true,
				Sensitive:   false,
				ForceNew:    false,
				WriteOnly:   false,
				Description: "Position of the group on the status page's top-level list",
			},

			"collapsed_by_default": &schema.Schema{
				Type:        schema.TypeBool,
				Computed:    true,
				Required:    false,
				Optional:    true,
				Sensitive:   false,
				ForceNew:    false,
				WriteOnly:   false,
				Description: "Whether the group renders collapsed on the public page. Value must be one of true or false",
			},
		},
	}
}

func resourceStatusPageComponentGroupCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*client.Client)

	tflog.Trace(ctx, fmt.Sprintf("Creating StatusPageComponentGroup"))

	s := &client.StatusPageComponentGroup{}

	if value, ok := d.GetOkExists("status_page_id"); ok {
		s.StatusPageId = value.(string)
	}
	if value, ok := d.GetOkExists("name"); ok {
		s.Name = value.(string)
	}
	if value, ok := d.GetOkExists("description"); ok {
		s.Description = value.(string)
	}
	if value, ok := d.GetOkExists("position"); ok {
		s.Position = value.(int)
	}
	if value, ok := d.GetOkExists("collapsed_by_default"); ok {
		s.CollapsedByDefault = tools.Bool(value.(bool))
	}

	res, err := c.CreateStatusPageComponentGroup(s)
	if err != nil {
		return diag.Errorf("Error creating status_page_component_group: %s", err.Error())
	}

	d.SetId(res.ID)
	tflog.Trace(ctx, fmt.Sprintf("created a status_page_component_group resource: %s", d.Id()))

	return resourceStatusPageComponentGroupRead(ctx, d, meta)
}

func resourceStatusPageComponentGroupRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*client.Client)
	tflog.Trace(ctx, fmt.Sprintf("Reading StatusPageComponentGroup: %s", d.Id()))

	item, err := c.GetStatusPageComponentGroup(d.Id())
	if err != nil {
		// In the case of a NotFoundError, it means the resource may have been removed upstream
		// We just remove it from the state.
		if errors.Is(err, client.NewNotFoundError("")) && !d.IsNewResource() {
			tflog.Warn(ctx, fmt.Sprintf("StatusPageComponentGroup (%s) not found, removing from state", d.Id()))
			d.SetId("")
			return nil
		}

		return diag.Errorf("Error reading status_page_component_group: %s", d.Id())
	}

	d.Set("status_page_id", item.StatusPageId)
	d.Set("name", item.Name)
	d.Set("description", item.Description)
	d.Set("position", item.Position)
	d.Set("collapsed_by_default", item.CollapsedByDefault)

	return nil
}

func resourceStatusPageComponentGroupUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*client.Client)
	tflog.Trace(ctx, fmt.Sprintf("Updating StatusPageComponentGroup: %s", d.Id()))

	s := &client.StatusPageComponentGroup{}

	if d.HasChange("status_page_id") {
		s.StatusPageId = d.Get("status_page_id").(string)
	}
	if d.HasChange("name") {
		s.Name = d.Get("name").(string)
	}
	if d.HasChange("description") {
		s.Description = d.Get("description").(string)
	}
	if d.HasChange("position") {
		s.Position = d.Get("position").(int)
	}
	if d.HasChange("collapsed_by_default") {
		s.CollapsedByDefault = tools.Bool(d.Get("collapsed_by_default").(bool))
	}

	_, err := c.UpdateStatusPageComponentGroup(d.Id(), s)
	if err != nil {
		return diag.Errorf("Error updating status_page_component_group: %s", err.Error())
	}

	return resourceStatusPageComponentGroupRead(ctx, d, meta)
}

func resourceStatusPageComponentGroupDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(*client.Client)
	tflog.Trace(ctx, fmt.Sprintf("Deleting StatusPageComponentGroup: %s", d.Id()))

	err := c.DeleteStatusPageComponentGroup(d.Id())
	if err != nil {
		// In the case of a NotFoundError, it means the resource may have been removed upstream.
		// We just remove it from the state.
		if errors.Is(err, client.NewNotFoundError("")) && !d.IsNewResource() {
			tflog.Warn(ctx, fmt.Sprintf("StatusPageComponentGroup (%s) not found, removing from state", d.Id()))
			d.SetId("")
			return nil
		}
		return diag.Errorf("Error deleting status_page_component_group: %s", err.Error())
	}

	d.SetId("")

	return nil
}
