package provider

// This file was auto-generated by tools/gen_tasks.js

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccResourceWorkflowTaskCreateGoToMeeting(t *testing.T) {
	resource.UnitTest(t, resource.TestCase{
		PreCheck:          func() {
			testAccPreCheck(t)
		},
		ProviderFactories: providerFactories,
		Steps: []resource.TestStep {
			{
				Config: testAccResourceWorkflowTaskCreateGoToMeeting,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("rootly_workflow_incident.foo", "name", "test-workflow"),
				),
			},
			{
				Config: testAccResourceWorkflowTaskCreateGoToMeetingUpdate,
			},
		},
	})
}

const testAccResourceWorkflowTaskCreateGoToMeeting = `
resource "rootly_workflow_incident" "foo" {
  	name = "test-workflow"
	trigger_params {
		triggers = ["incident_updated"]
	}
}

resource "rootly_workflow_task_create_go_to_meeting" "foo" {
	workflow_id = rootly_workflow_incident.foo.id
	task_params {
		subject = "test"
	}
}
`

const testAccResourceWorkflowTaskCreateGoToMeetingUpdate = `
resource "rootly_workflow_incident" "foo" {
  	name = "test-workflow"
	trigger_params {
		triggers = ["incident_updated"]
	}
}

resource "rootly_workflow_task_create_go_to_meeting" "foo" {
	workflow_id = rootly_workflow_incident.foo.id
	task_params {
		subject = "test"
	}
}
`
