package provider

var RailsTimeZones = []string{
	"International Date Line West", "Etc/GMT+12",
	"American Samoa", "Pacific/Pago_Pago",
	"Midway Island", "Pacific/Midway",
	"Hawaii", "Pacific/Honolulu",
	"Alaska", "America/Juneau",
	"Pacific Time (US & Canada)", "America/Los_Angeles",
	"Tijuana", "America/Tijuana",
	"Arizona", "America/Phoenix",
	"Mazatlan", "America/Mazatlan",
	"Mountain Time (US & Canada)", "America/Denver",
	"Central America", "America/Guatemala",
	"Central Time (US & Canada)", "America/Chicago",
	"Chihuahua", "America/Chihuahua",
	"Guadalajara", "America/Mexico_City",
	"Mexico City", "America/Mexico_City",
	"Monterrey", "America/Monterrey",
	"Saskatchewan", "America/Regina",
	"Bogota", "America/Bogota",
	"Eastern Time (US & Canada)", "America/New_York",
	"Indiana (East)", "America/Indiana/Indianapolis",
	"Lima", "America/Lima",
	"Quito", "America/Lima",
	"Atlantic Time (Canada)", "America/Halifax",
	"Caracas", "America/Caracas",
	"Georgetown", "America/Guyana",
	"La Paz", "America/La_Paz",
	"Puerto Rico", "America/Puerto_Rico",
	"Santiago", "America/Santiago",
	"Newfoundland", "America/St_Johns",
	"Brasilia", "America/Sao_Paulo",
	"Buenos Aires", "America/Argentina/Buenos_Aires",
	"Montevideo", "America/Montevideo",
	"Greenland", "America/Godthab",
	"Mid-Atlantic", "Atlantic/South_Georgia",
	"Azores", "Atlantic/Azores",
	"Cape Verde Is.", "Atlantic/Cape_Verde",
	"Casablanca", "Africa/Casablanca",
	"Dublin", "Europe/Dublin",
	"Edinburgh", "Europe/London",
	"Lisbon", "Europe/Lisbon",
	"London", "Europe/London",
	"Monrovia", "Africa/Monrovia",
	"UTC", "Etc/UTC",
	"Amsterdam", "Europe/Amsterdam",
	"Belgrade", "Europe/Belgrade",
	"Berlin", "Europe/Berlin",
	"Bern", "Europe/Zurich",
	"Bratislava", "Europe/Bratislava",
	"Brussels", "Europe/Brussels",
	"Budapest", "Europe/Budapest",
	"Copenhagen", "Europe/Copenhagen",
	"Ljubljana", "Europe/Ljubljana",
	"Madrid", "Europe/Madrid",
	"Paris", "Europe/Paris",
	"Prague", "Europe/Prague",
	"Rome", "Europe/Rome",
	"Sarajevo", "Europe/Sarajevo",
	"Skopje", "Europe/Skopje",
	"Stockholm", "Europe/Stockholm",
	"Vienna", "Europe/Vienna",
	"Warsaw", "Europe/Warsaw",
	"West Central Africa", "Africa/Algiers",
	"Zagreb", "Europe/Zagreb",
	"Zurich", "Europe/Zurich",
	"Athens", "Europe/Athens",
	"Bucharest", "Europe/Bucharest",
	"Cairo", "Africa/Cairo",
	"Harare", "Africa/Harare",
	"Helsinki", "Europe/Helsinki",
	"Jerusalem", "Asia/Jerusalem",
	"Kaliningrad", "Europe/Kaliningrad",
	"Kyiv", "Europe/Kiev",
	"Pretoria", "Africa/Johannesburg",
	"Riga", "Europe/Riga",
	"Sofia", "Europe/Sofia",
	"Tallinn", "Europe/Tallinn",
	"Vilnius", "Europe/Vilnius",
	"Baghdad", "Asia/Baghdad",
	"Istanbul", "Europe/Istanbul",
	"Kuwait", "Asia/Kuwait",
	"Minsk", "Europe/Minsk",
	"Moscow", "Europe/Moscow",
	"Nairobi", "Africa/Nairobi",
	"Riyadh", "Asia/Riyadh",
	"St. Petersburg", "Europe/Moscow",
	"Volgograd", "Europe/Volgograd",
	"Tehran", "Asia/Tehran",
	"Abu Dhabi", "Asia/Muscat",
	"Baku", "Asia/Baku",
	"Muscat", "Asia/Muscat",
	"Samara", "Europe/Samara",
	"Tbilisi", "Asia/Tbilisi",
	"Yerevan", "Asia/Yerevan",
	"Kabul", "Asia/Kabul",
	"Almaty", "Asia/Almaty",
	"Astana", "Asia/Almaty",
	"Ekaterinburg", "Asia/Yekaterinburg",
	"Islamabad", "Asia/Karachi",
	"Karachi", "Asia/Karachi",
	"Tashkent", "Asia/Tashkent",
	"Chennai", "Asia/Kolkata",
	"Kolkata", "Asia/Kolkata",
	"Mumbai", "Asia/Kolkata",
	"New Delhi", "Asia/Kolkata",
	"Sri Jayawardenepura", "Asia/Colombo",
	"Kathmandu", "Asia/Kathmandu",
	"Dhaka", "Asia/Dhaka",
	"Urumqi", "Asia/Urumqi",
	"Rangoon", "Asia/Rangoon",
	"Bangkok", "Asia/Bangkok",
	"Hanoi", "Asia/Bangkok",
	"Jakarta", "Asia/Jakarta",
	"Krasnoyarsk", "Asia/Krasnoyarsk",
	"Novosibirsk", "Asia/Novosibirsk",
	"Beijing", "Asia/Shanghai",
	"Chongqing", "Asia/Chongqing",
	"Hong Kong", "Asia/Hong_Kong",
	"Irkutsk", "Asia/Irkutsk",
	"Kuala Lumpur", "Asia/Kuala_Lumpur",
	"Perth", "Australia/Perth",
	"Singapore", "Asia/Singapore",
	"Taipei", "Asia/Taipei",
	"Ulaanbaatar", "Asia/Ulaanbaatar",
	"Osaka", "Asia/Tokyo",
	"Sapporo", "Asia/Tokyo",
	"Seoul", "Asia/Seoul",
	"Tokyo", "Asia/Tokyo",
	"Yakutsk", "Asia/Yakutsk",
	"Adelaide", "Australia/Adelaide",
	"Darwin", "Australia/Darwin",
	"Brisbane", "Australia/Brisbane",
	"Canberra", "Australia/Canberra",
	"Guam", "Pacific/Guam",
	"Hobart", "Australia/Hobart",
	"Melbourne", "Australia/Melbourne",
	"Port Moresby", "Pacific/Port_Moresby",
	"Sydney", "Australia/Sydney",
	"Vladivostok", "Asia/Vladivostok",
	"Magadan", "Asia/Magadan",
	"New Caledonia", "Pacific/Noumea",
	"Solomon Is.", "Pacific/Guadalcanal",
	"Srednekolymsk", "Asia/Srednekolymsk",
	"Auckland", "Pacific/Auckland",
	"Fiji", "Pacific/Fiji",
	"Kamchatka", "Asia/Kamchatka",
	"Marshall Is.", "Pacific/Majuro",
	"Wellington", "Pacific/Auckland",
	"Chatham Is.", "Pacific/Chatham",
	"Nuku'alofa", "Pacific/Tongatapu",
	"Samoa", "Pacific/Apia",
	"Tokelau Is.", "Pacific/Fakaofo",
}

// IANATimeZones contains only IANA standard timezone identifiers.
// Used by fields that require the IANA format (e.g. deferral_window rule time_zone).
var IANATimeZones = []string{
	"Africa/Algiers",
	"Africa/Cairo",
	"Africa/Casablanca",
	"Africa/Harare",
	"Africa/Johannesburg",
	"Africa/Monrovia",
	"Africa/Nairobi",
	"America/Argentina/Buenos_Aires",
	"America/Asuncion",
	"America/Bogota",
	"America/Caracas",
	"America/Chicago",
	"America/Chihuahua",
	"America/Denver",
	"America/Guatemala",
	"America/Guyana",
	"America/Halifax",
	"America/Indiana/Indianapolis",
	"America/Juneau",
	"America/La_Paz",
	"America/Lima",
	"America/Los_Angeles",
	"America/Mazatlan",
	"America/Mexico_City",
	"America/Monterrey",
	"America/Montevideo",
	"America/New_York",
	"America/Nuuk",
	"America/Phoenix",
	"America/Puerto_Rico",
	"America/Regina",
	"America/Santiago",
	"America/Sao_Paulo",
	"America/St_Johns",
	"America/Tijuana",
	"Asia/Almaty",
	"Asia/Baghdad",
	"Asia/Baku",
	"Asia/Bangkok",
	"Asia/Chongqing",
	"Asia/Colombo",
	"Asia/Dhaka",
	"Asia/Hong_Kong",
	"Asia/Irkutsk",
	"Asia/Jakarta",
	"Asia/Jerusalem",
	"Asia/Kabul",
	"Asia/Kamchatka",
	"Asia/Karachi",
	"Asia/Kathmandu",
	"Asia/Kolkata",
	"Asia/Krasnoyarsk",
	"Asia/Kuala_Lumpur",
	"Asia/Kuwait",
	"Asia/Magadan",
	"Asia/Muscat",
	"Asia/Novosibirsk",
	"Asia/Rangoon",
	"Asia/Riyadh",
	"Asia/Seoul",
	"Asia/Shanghai",
	"Asia/Singapore",
	"Asia/Srednekolymsk",
	"Asia/Taipei",
	"Asia/Tashkent",
	"Asia/Tbilisi",
	"Asia/Tehran",
	"Asia/Tokyo",
	"Asia/Ulaanbaatar",
	"Asia/Urumqi",
	"Asia/Vladivostok",
	"Asia/Yakutsk",
	"Asia/Yekaterinburg",
	"Asia/Yerevan",
	"Atlantic/Azores",
	"Atlantic/Cape_Verde",
	"Atlantic/South_Georgia",
	"Australia/Adelaide",
	"Australia/Brisbane",
	"Australia/Canberra",
	"Australia/Darwin",
	"Australia/Hobart",
	"Australia/Melbourne",
	"Australia/Perth",
	"Australia/Sydney",
	"Etc/GMT+12",
	"Etc/UTC",
	"Europe/Amsterdam",
	"Europe/Athens",
	"Europe/Belgrade",
	"Europe/Berlin",
	"Europe/Bratislava",
	"Europe/Brussels",
	"Europe/Bucharest",
	"Europe/Budapest",
	"Europe/Copenhagen",
	"Europe/Dublin",
	"Europe/Helsinki",
	"Europe/Istanbul",
	"Europe/Kaliningrad",
	"Europe/Kiev",
	"Europe/Lisbon",
	"Europe/Ljubljana",
	"Europe/London",
	"Europe/Madrid",
	"Europe/Minsk",
	"Europe/Moscow",
	"Europe/Paris",
	"Europe/Prague",
	"Europe/Riga",
	"Europe/Rome",
	"Europe/Samara",
	"Europe/Sarajevo",
	"Europe/Skopje",
	"Europe/Sofia",
	"Europe/Stockholm",
	"Europe/Tallinn",
	"Europe/Vienna",
	"Europe/Vilnius",
	"Europe/Volgograd",
	"Europe/Warsaw",
	"Europe/Zagreb",
	"Europe/Zurich",
	"Pacific/Apia",
	"Pacific/Auckland",
	"Pacific/Chatham",
	"Pacific/Fakaofo",
	"Pacific/Fiji",
	"Pacific/Guadalcanal",
	"Pacific/Guam",
	"Pacific/Honolulu",
	"Pacific/Majuro",
	"Pacific/Midway",
	"Pacific/Noumea",
	"Pacific/Pago_Pago",
	"Pacific/Port_Moresby",
	"Pacific/Tongatapu",
}
